/* eslint-disable @typescript-eslint/explicit-function-return-type */
import { tags } from "@lezer/highlight";

const EDITOR_TAGS = {
  titleKey: tags.attributeName,
  titleValue: tags.attributeValue,
  section: tags.heading,
  sectionName: tags.labelName,
  scene: tags.regexp,
  sceneNumber: tags.number,
  transition: tags.unit,
  variableName: tags.variableName,
  parameterName: tags.function(tags.variableName),
  dialogue_character: tags.className,
  dialogue_parenthetical: tags.tagName,
  dialogue: tags.name,
  dualDialogue: tags.typeOperator,
  lyric: tags.annotation,
  pageBreak: tags.contentSeparator,
  note: tags.meta,
  synopsis: tags.lineComment,
  centered: tags.quote,
  underline: tags.link,
  emphasis: tags.emphasis,
  strong: tags.strong,
  conditionCheck: tags.logicOperator,
  comment: tags.comment,
  commentBlock: tags.blockComment,
  escape: tags.escape,
  structName: tags.character,
  structBase: tags.special(tags.character),
  structFieldName: tags.special(tags.propertyName),
  link: tags.link,
  image: tags.link,
  orderedList: tags.list,
  bulletList: tags.list,
  inlineCode: tags.monospace,
  codeText: tags.monospace,
  url: tags.url,
  paragraph: tags.content,
  hardBreak: tags.processingInstruction,
  pause: tags.changed,

  sectionMark: tags.heading1,
  sceneMark: tags.heading2,
  lyricMark: tags.processingInstruction,
  noteMark: tags.standard(tags.meta),
  synopsisMark: tags.standard(tags.lineComment),
  centeredMark: tags.processingInstruction,
  emphasisMark: tags.processingInstruction,
  underlineMark: tags.processingInstruction,
  quoteMark: tags.processingInstruction,
  linkMark: tags.processingInstruction,
  strikethrough: tags.strikethrough,
  formatting: tags.processingInstruction,
  codeMark: tags.special(tags.processingInstruction),

  typeName: tags.typeName,
  keyword: tags.keyword,
  string: tags.string,
  number: tags.number,
  boolean: tags.bool,

  invalid: tags.invalid,
};

export default EDITOR_TAGS;
