/** Each percussion instrument can only be played at one pitch */
export const MIDI_PERCUSSION_INSTRUMENTS = {
  /* 0-34 : None */
  "00": "",
  "01": "",
  "02": "",
  "03": "",
  "04": "",
  "05": "",
  "06": "",
  "07": "",
  "08": "",
  "09": "",
  "10": "",
  "11": "",
  "12": "",
  "13": "",
  "14": "",
  "15": "",
  "16": "",
  "17": "",
  "18": "",
  "19": "",
  "20": "",
  "21": "",
  "22": "",
  "23": "",
  "24": "",
  "25": "",
  "26": "",
  "27": "",
  "28": "",
  "29": "",
  "30": "",
  "31": "",
  "32": "",
  "33": "",
  "34": "",

  /* 35-81 : Percussion */
  percussion_drum_bass_acoustic: "Acoustic Bass Drum",
  percussion_drum_bass_1: "Bass Drum 1",
  percussion_drum_stick: "Side Stick",
  percussion_snare_acoustic: "Acoustic Snare",
  percussion_clap: "Hand Clap",
  percussion_snare_electric: "Electric Snare",
  percussion_drum_tom_low_floor: "Low Floor Tom",
  percussion_hihat_closed: "Closed Hi Hat",
  percussion_drum_tom_high_floor: "High Floor Tom",
  percussion_hihat_pedal: "Pedal Hi-Hat",
  percussion_drum_tom_low: "Low Tom",
  percussion_highat_open: "Open Hi-Hat",
  percussion_drum_tom_low_mid: "Low-Mid Tom",
  percussion_drum_tom_high_mid: "High-Mid Tom",
  percussion_cymbal_crash_1: "Crash Cymbal 1",
  percussion_drum_tom_high: "High Tom",
  percussion_cymbal_ride_1: "Ride Cymbal 1",
  percussion_cymbal_china: "Chinese Cymbal",
  percussion_cymbal_ride_bell: "Ride Bell",
  percussion_tambourine: "Tambourine",
  percussion_cymbal_splash: "Splash Cymbal",
  percussion_cowbell: "Cowbell",
  percussion_cymbal_crash_2: "Crash Cymbal 2",
  percussion_vibraslap: "Vibraslap",
  percussion_cymbal_ride_2: "Ride Cymbal 2",
  percussion_drum_bongo_high: "High Bongo",
  percussion_drum_bongo_low: "Low Bongo",
  percussion_drum_conga_high_muted: "Mute High Conga",
  percussion_drum_conga_high_open: "Open Hi Conga",
  percussion_drum_conga_low: "Low Conga",
  percussion_drum_timbale_high: "High Timbale",
  percussion_drum_timbale_low: "Low Timbale",
  percussion_agogo_high: "High Agogo",
  percussion_agogo_low: "Low Agogo",
  percussion_cabasa: "Cabasa",
  percussion_maracas: "Maracas",
  percussion_whistle_short: "Short Whistle",
  percussion_whistle_long: "Long Whistle",
  percussion_guiro_short: "Short Guiro",
  percussion_guiro_long: "Long Guiro",
  percussion_claves: "Claves",
  percussion_woodblock_high: "Hi Wood Block",
  percussion_woodblock_low: "Low Wood Block",
  percussion_drum_cuica_muted: "Mute Cuica",
  percussion_drum_cuica_open: "Open Cuica",
  percussion_triangle_muted: "Mute Triangle",
  percussion_triangle_open: "Open Triangle",
} as const;
