availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_API_KEY/versions/1
      env: BROWSER_GOOGLE_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_OAUTH_CLIENT_ID/versions/1
      env: BROWSER_GOOGLE_OAUTH_CLIENT_ID

steps:
  # 1) Install & build with secrets available to the process.env of Node
  - name: node:20-slim
    entrypoint: bash
    args:
      - -lc
      - |
        cd ./impower-dev
        npm ci
        npm run postinstall
        npm run build
        cd ../
    secretEnv:
      - BROWSER_GOOGLE_API_KEY
      - BROWSER_GOOGLE_OAUTH_CLIENT_ID
    env:
      - VITE_SPARKDOWN_PLAYER_ORIGIN=$_VITE_SPARKDOWN_PLAYER_ORIGIN
  # 2) Build a small runtime image from the compiled output
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - impower-dev
      - "-f"
      - impower-dev/Dockerfile
    id: Build
  # 3) Push image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  # 4) Deploy to Google Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud

images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _TRIGGER_ID: 2c503cf9-ee20-4fe8-8dd3-6e3a1d3ab3eb
  _SERVICE_NAME: impower
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: impower-dev-client
  _PLATFORM: managed

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - impower
