const STYLE_PROPS = {};

export const STYLE_DEFAULTS = {
  default: {
    ...STYLE_PROPS,
    xs: STYLE_PROPS,
    sm: STYLE_PROPS,
    md: STYLE_PROPS,
    lg: STYLE_PROPS,
    xl: STYLE_PROPS,
    hovered: STYLE_PROPS,
    pressed: STYLE_PROPS,
    focused: STYLE_PROPS,
    checked: STYLE_PROPS,
    disabled: STYLE_PROPS,
  },
  all: {
    target: "*, *::before, *::after",
    box_sizing: "border-box",
  },
  is_hidden: {
    target: "[hidden]",
    display: "none",
  },
  text: {
    pointer_events: "auto",
    position: "relative",
    white_space: "pre-line",
    "*": {
      position: "relative",
    },
  },
  image: {
    position: "absolute",
    pointer_events: "auto",
    inset: 0,
    "*": {
      position: "absolute",
      inset: "0",
      background_position: "center",
      background_repeat: "no-repeat",
      background_size: "auto 100%",
    },
  },
  loading_bar: {
    z_index: 1000,
    position: "relative",
    width: "100%",
    height: 4,
  },
  loading_fill: {
    width: "100%",
    height: "100%",
    background_color: "cyan50",
    transform: "scaleX(var(--loading_progress))",
    transform_origin: "left",
  },
  screen: {
    position: "absolute",
    inset: 0,
    pointer_events: "none",
  },
  background: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flex_direction: "column",
  },
  backdrop: {
    preserve_image: true,
    position: "absolute",
    inset: 0,
    background_position: "center",
    background_size: "cover",
  },
  portrait: {
    position: "absolute",
    top: "10%",
    right: 0,
    bottom: 0,
    left: 0,
    display: "flex",
    flex_direction: "column",
    background_size: "auto 100%",
    background_position: "center",
  },
  middle: {
    position: "relative",
    flex: 1,
    display: "flex",
    flex_direction: "column",
    align_items: "center",
    justify_content: "center",
    font_size: "1rem",
    md: {
      font_size: "1.125rem",
    },
  },
  choices: {
    display: "flex",
    flex_direction: "column",
    align_items: "center",
    justify_content: "center",
    width: "100%",
    padding: 8,
  },
  choice: {
    background_color: "white",
    color: "black",
    padding: 8,
    margin: "8px 0",
    width: "90%",
    max_width: 800,
    text_align: "center",
    opacity: "0",
  },
  bottom: {
    position: "relative",
    display: "flex",
    flex_direction: "column",
    align_content: "center",
    max_height: 224,
    height: "100%",
  },
  textbox: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    display: "flex",
    flex_direction: "column",
    align_content: "center",
    max_width: 800,
    height: 200,
    width: "100%",
    margin: "0 auto",
    color: "black",
    flex: 1,
    padding: 16,
    md: { padding_left: 32, padding_right: 32, font_size: "1.125rem" },
  },
  box_background: {
    position: "absolute",
    inset: 0,
    background_color: "white",
  },
  content: {
    position: "relative",
    flex: 1,
    display: "flex",
    flex_direction: "column",
    font_size: "1rem",
  },
  dialogue_group: {
    display: "flex",
    flex_direction: "column",
  },
  character_name: {
    display: "block",
    text_align: "center",
    line_height: 1,
    font_size: "1.5rem",
    md: { font_size: "1.75rem" },
  },
  character_parenthetical: {
    display: "block",
    text_align: "center",
    line_height: 1,
    font_size: "1.5rem",
    md: { font_size: "1.75rem" },
  },
  dialogue_content: {
    width: "80%",
    margin: "0 auto",
    md: { width: "68%" },
  },
  parenthetical: {
    display: "block",
    text_align: "center",
    position: "relative",
    min_height: "0.5em",
  },
  dialogue: {
    flex: 1,
  },
  action: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flex_direction: "column",
    justify_content: "center",
    align_self: "center",
    text_align: "center",
  },
  transition: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flex_direction: "column",
    justify_content: "center",
    align_self: "flex-end",
    text_align: "right",
    width: "100%",
  },
  scene: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flex_direction: "column",
    justify_content: "center",
    align_self: "center",
    text_align: "center",
    font_weight: "bold",
  },
  indicator: {
    width: 16,
    height: 16,
    position: "absolute",
    right: 16,
    bottom: 16,
    transition: `opacity 0.25s linear`,
    animation: "0.5s infinite bounce",
    animation_play_state: "paused",
  },
};
