import {
  getCssAnimation,
  getCssBgAlign,
  getCssBgFit,
  getCssBlend,
  getCssBorderStyle,
  getCssChildAlign,
  getCssChildJustify,
  getCssChildLayout,
  getCssChildOverflow,
  getCssColor,
  getCssColumns,
  getCssContainIntrinsicSize,
  getCssContentVisibility,
  getCssCorner,
  getCssDimension,
  getCssDuration,
  getCssEase,
  getCssFilter,
  getCssFlex,
  getCssGradient,
  getCssGrow,
  getCssImage,
  getCssInteractable,
  getCssInvisible,
  getCssMask,
  getCssOutlineStyle,
  getCssOverflow,
  getCssPattern,
  getCssPosition,
  getCssRatio,
  getCssRepeat,
  getCssRing,
  getCssRotate,
  getCssScale,
  getCssSelectable,
  getCssShadow,
  getCssShadowInset,
  getCssShrink,
  getCssSize,
  getCssSkew,
  getCssTextAlign,
  getCssTextFont,
  getCssTextItalic,
  getCssTextLeading,
  getCssTextOverflow,
  getCssTextSize,
  getCssTextStrikethrough,
  getCssTextUnderline,
  getCssTextWeight,
  getCssTextWhitespace,
  getCssTranslate,
  getCssVisible,
  getCssZ,
} from "../utils/transformers.js";

const get = (v: string) => v;

const STYLE_TRANSFORMERS = {
  display: get,

  position: getCssPosition,

  aspect: getCssRatio,

  overflow: getCssOverflow,
  "overflow-x": getCssOverflow,
  "overflow-y": getCssOverflow,

  z: getCssZ,

  width: getCssDimension,
  "width-min": getCssDimension,
  "width-max": getCssDimension,

  height: getCssDimension,
  "height-min": getCssDimension,
  "height-max": getCssDimension,

  corner: getCssCorner,
  "corner-t": getCssCorner,
  "corner-r": getCssCorner,
  "corner-b": getCssCorner,
  "corner-l": getCssCorner,
  "corner-tl": getCssCorner,
  "corner-tr": getCssCorner,
  "corner-br": getCssCorner,
  "corner-bl": getCssCorner,

  inset: getCssSize,
  "inset-t": getCssSize,
  "inset-r": getCssSize,
  "inset-b": getCssSize,
  "inset-l": getCssSize,
  "inset-lr": getCssSize,
  "inset-tb": getCssSize,

  "outline-width": getCssSize,
  "outline-color": getCssColor,
  "outline-style": getCssOutlineStyle,

  "border-width": getCssSize,
  "border-width-t": getCssSize,
  "border-width-r": getCssSize,
  "border-width-b": getCssSize,
  "border-width-l": getCssSize,
  "border-width-lr": getCssSize,
  "border-width-tb": getCssSize,
  "border-color": getCssColor,
  "border-color-t": getCssColor,
  "border-color-r": getCssColor,
  "border-color-b": getCssColor,
  "border-color-l": getCssColor,
  "border-color-lr": getCssColor,
  "border-color-tb": getCssColor,
  "border-style": getCssBorderStyle,
  "border-style-t": getCssBorderStyle,
  "border-style-r": getCssBorderStyle,
  "border-style-b": getCssBorderStyle,
  "border-style-l": getCssBorderStyle,
  "border-style-lr": getCssBorderStyle,
  "border-style-tb": getCssBorderStyle,

  margin: getCssSize,
  "margin-t": getCssSize,
  "margin-r": getCssSize,
  "margin-b": getCssSize,
  "margin-l": getCssSize,
  "margin-lr": getCssSize,
  "margin-tb": getCssSize,

  padding: getCssSize,
  "padding-t": getCssSize,
  "padding-r": getCssSize,
  "padding-b": getCssSize,
  "padding-l": getCssSize,
  "padding-lr": getCssSize,
  "padding-tb": getCssSize,

  "child-layout": getCssChildLayout,
  "child-gap": getCssSize,
  "child-align": getCssChildAlign,
  "child-justify": getCssChildJustify,
  "child-overflow": getCssChildOverflow,
  "self-align": getCssChildAlign,
  columns: getCssColumns,

  flex: getCssFlex,
  grow: getCssGrow,
  shrink: getCssShrink,

  invisible: getCssInvisible,
  visible: getCssVisible,
  interactable: getCssInteractable,
  selectable: getCssSelectable,

  color: getCssColor,

  "text-font": getCssTextFont,
  "text-size": getCssTextSize,
  "text-leading": getCssTextLeading,
  "text-kerning": get,
  "text-weight": getCssTextWeight,
  "text-italic": getCssTextItalic,
  "text-underline": getCssTextUnderline,
  "text-strikethrough": getCssTextStrikethrough,
  "text-case": get,
  "text-align": getCssTextAlign,
  "text-overflow": getCssTextOverflow,
  "text-whitespace": getCssTextWhitespace,
  "text-color": getCssColor,
  "text-stroke-color": getCssColor,
  "text-stroke-width": get,
  "text-underline-offset": getCssSize,
  "text-decoration-thickness": getCssSize,

  "background-color": getCssColor,
  "background-gradient": getCssGradient,
  "background-pattern": getCssPattern,
  "background-image": getCssImage,
  "background-repeat": getCssRepeat,
  "background-align": getCssBgAlign,
  "background-fit": getCssBgFit,

  mask: getCssMask,

  shadow: getCssShadow,
  "shadow-inset": getCssShadowInset,

  ring: getCssRing,
  "ring-color": getCssColor,
  "ring-width": getCssSize,

  filter: getCssFilter,

  blend: getCssBlend,

  opacity: get,

  "translate-x": getCssTranslate,
  "translate-y": getCssTranslate,
  "translate-z": getCssTranslate,
  "rotate-x": get,
  "rotate-y": get,
  "rotate-z": get,
  rotate: getCssRotate,
  "scale-x": getCssScale,
  "scale-y": getCssScale,
  "scale-z": getCssScale,
  "skew-x": getCssSkew,
  "skew-y": getCssSkew,

  pivot: get,

  delay: getCssDuration,
  duration: getCssDuration,
  ease: getCssEase,

  animation: getCssAnimation,
  exit: getCssAnimation,
  enter: getCssAnimation,

  "content-visibility": getCssContentVisibility,
  "contain-intrinsic-size": getCssContainIntrinsicSize,
} as const;

export default STYLE_TRANSFORMERS;
