import {
  getCssAnimation,
  getCssBgAlign,
  getCssBgFit,
  getCssBlend,
  getCssBorderStyle,
  getCssChildAlign,
  getCssChildColumns,
  getCssChildJustify,
  getCssChildLayout,
  getCssChildOverflow,
  getCssColor,
  getCssContainIntrinsicSize,
  getCssContentVisibility,
  getCssCorner,
  getCssDimension,
  getCssDuration,
  getCssEase,
  getCssFilter,
  getCssFlex,
  getCssGrow,
  getCssImage,
  getCssInteractable,
  getCssMask,
  getCssOrder,
  getCssOutlineStyle,
  getCssOverflow,
  getCssPosition,
  getCssRatio,
  getCssRepeat,
  getCssRing,
  getCssRotate,
  getCssScale,
  getCssSelectable,
  getCssShadow,
  getCssShadowInset,
  getCssShrink,
  getCssSize,
  getCssTextAlign,
  getCssTextDecorationLine,
  getCssTextFont,
  getCssTextLeading,
  getCssTextOverflow,
  getCssTextSize,
  getCssTextStroke,
  getCssTextStyle,
  getCssTextWeight,
  getCssTextWhitespace,
  getCssTranslate,
  getCssVisible,
  getCssZ,
} from "../utils/transformers.js";

const get = (v: string) => v;

const STYLE_TRANSFORMERS = {
  display: get,

  position: getCssPosition,

  aspect: getCssRatio,

  overflow: getCssOverflow,
  "overflow-x": getCssOverflow,
  "overflow-y": getCssOverflow,

  z: getCssZ,

  width: getCssDimension,
  "width-min": getCssDimension,
  "width-max": getCssDimension,

  height: getCssDimension,
  "height-min": getCssDimension,
  "height-max": getCssDimension,

  corner: getCssCorner,
  "corner-top-left": getCssCorner,
  "corner-top-right": getCssCorner,
  "corner-bottom-right": getCssCorner,
  "corner-bottom-left": getCssCorner,

  "outline-width": getCssSize,
  "outline-color": getCssColor,
  "outline-style": getCssOutlineStyle,

  "border-width": getCssSize,
  "border-width-top": getCssSize,
  "border-width-right": getCssSize,
  "border-width-bottom": getCssSize,
  "border-width-left": getCssSize,
  "border-color": getCssColor,
  "border-color-top": getCssColor,
  "border-color-right": getCssColor,
  "border-color-bottom": getCssColor,
  "border-color-left": getCssColor,
  "border-style": getCssBorderStyle,
  "border-style-top": getCssBorderStyle,
  "border-style-right": getCssBorderStyle,
  "border-style-bottom": getCssBorderStyle,
  "border-style-left": getCssBorderStyle,

  inset: getCssSize,
  "inset-top": getCssSize,
  "inset-right": getCssSize,
  "inset-bottom": getCssSize,
  "inset-left": getCssSize,

  margin: getCssSize,
  "margin-top": getCssSize,
  "margin-right": getCssSize,
  "margin-bottom": getCssSize,
  "margin-left": getCssSize,

  padding: getCssSize,
  "padding-top": getCssSize,
  "padding-right": getCssSize,
  "padding-bottom": getCssSize,
  "padding-left": getCssSize,

  "child-layout": getCssChildLayout,
  "child-columns": getCssChildColumns,
  "child-gap": getCssSize,
  "child-align": getCssChildAlign,
  "child-justify": getCssChildJustify,
  "child-overflow": getCssChildOverflow,

  "self-align": getCssChildAlign,

  flex: getCssFlex,
  grow: getCssGrow,
  shrink: getCssShrink,
  order: getCssOrder,

  visible: getCssVisible,
  interactable: getCssInteractable,
  selectable: getCssSelectable,

  cursor: get,

  "text-font": getCssTextFont,
  "text-size": getCssTextSize,
  "text-leading": getCssTextLeading,
  "text-tracking": get,
  "text-weight": getCssTextWeight,
  "text-style": getCssTextStyle,
  "text-case": get,
  "text-align": getCssTextAlign,
  "text-overflow": getCssTextOverflow,
  "text-whitespace": getCssTextWhitespace,
  "text-color": getCssColor,
  "text-stroke": getCssTextStroke,
  "text-decoration-line": getCssTextDecorationLine,
  "text-decoration-color": getCssColor,
  "text-decoration-thickness": getCssSize,
  "text-underline-offset": getCssSize,

  "background-color": getCssColor,
  "background-image": getCssImage,
  "background-repeat": getCssRepeat,
  "background-align": getCssBgAlign,
  "background-fit": getCssBgFit,

  mask: getCssMask,

  shadow: getCssShadow,
  "shadow-inset": getCssShadowInset,
  ring: getCssRing,

  filter: getCssFilter,
  "backdrop-filter": getCssFilter,

  blend: getCssBlend,

  opacity: get,

  translate: getCssTranslate,
  rotate: getCssRotate,
  scale: getCssScale,

  pivot: get,

  "transition-delay": getCssDuration,
  "transition-duration": getCssDuration,
  "transition-easing": getCssEase,

  animation: getCssAnimation,
  exit: getCssAnimation,
  enter: getCssAnimation,

  "content-visibility": getCssContentVisibility,
  "contain-intrinsic-size": getCssContainIntrinsicSize,
} as const;

export default STYLE_TRANSFORMERS;
