export type SparkFrontMatterKeyword =
  | "title"
  | "credit"
  | "author"
  | "authors"
  | "source"
  | "watermark"
  | "font"
  | "language"
  | "notes"
  | "copyright"
  | "revision"
  | "date"
  | "draft_date"
  | "contact"
  | "contact_info"
  | "header"
  | "footer";
