export const pageNames: { [baseRoute: string]: string } = {
  "/account": "Account",
  "/profile": "Profile",
  "/logout": "Logout",
  "/signup": "Sign Up",
  "/confirm": "Confirm",
  "/login": "Login",
  "/": "Home",
  "/pitch": "Pitch",
  "/library": "Library",
  "/dashboard": "Dashboard",
  "#donate": "Donate",
  "/invite": "Invite",
  "/contact": "Contact",
  "/g": "Game",
  "/r": "Project",
  "/s": "Studio",
  "/u": "Profile",
};
