import { SparkStyleProperties } from "../../..";
import { RecursiveValidation } from "../../../core/types/RecursiveValidation";

const GRID_STEP = 8;

export const STYLE_PROPS_VALIDATION = (typeMap?: {
  [type: string]: Record<string, object>;
}): RecursiveValidation<SparkStyleProperties> => {
  const colorNames = Object.keys(typeMap?.["color"] || {});
  const gradientNames = Object.keys(typeMap?.["gradient"] || {});
  const patternNames = Object.keys(typeMap?.["pattern"] || {});
  const imageNames = Object.keys(typeMap?.["image"] || {});
  const animationNames = Object.keys(typeMap?.["animation"] || {});
  const easeNames = Object.keys(typeMap?.["ease"] || {});
  const fontNames = Object.keys(typeMap?.["font"] || {});
  const pathNames = Object.keys(typeMap?.["path"] || {});
  return {
    position: ["default", "relative", "fixed", "absolute", "sticky"],
    aspect: ["1/1", "16/9", "9/16", "4/5", "2/3", "2/1"],
    overflowX: ["visible", "scroll", "clip"],
    overflowY: ["visible", "scroll", "clip"],
    z: [1, 0, 10],
    width: ["100%", "min-content", "max-content"],
    widthMin: ["100%", "min-content", "max-content"],
    widthMax: ["100%", "min-content", "max-content"],
    height: ["100%", "min-content", "max-content"],
    heightMin: ["100%", "min-content", "max-content"],
    heightMax: ["100%", "min-content", "max-content"],
    corner: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    cornerT: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    cornerR: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    cornerB: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    cornerL: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    cornerTL: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    cornerTR: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    cornerBR: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    cornerBL: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    inset: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    insetT: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    insetR: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    insetB: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    insetL: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    insetLR: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    insetTB: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    margin: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    marginT: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    marginR: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    marginB: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    marginL: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    marginLR: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    marginTB: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    padding: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    paddingT: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    paddingR: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    paddingB: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    paddingL: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    paddingLR: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    paddingTB: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    childLayout: ["row", "column", "row-reverse", "column-reverse"],
    childGap: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    childAlign: ["center", "stretch", "start", "end"],
    childJustify: [
      "center",
      "stretch",
      "start",
      "end",
      "between",
      "around",
      "evenly",
    ],
    selfAlign: ["center", "stretch", "start", "end"],
    overflowOverflow: ["visible", "wrap", "wrap-reverse"],
    grow: [1, 0, 10],
    shrink: [0, 0, 10],
    fill: ["none", ...colorNames],
    stroke: ["none", ...colorNames],
    strokeWidth: [1, 0, 10],
    color: ["none", ...colorNames],
    textFont: ["sans", "serif", "mono", ...fontNames],
    textSize: [
      "2xs",
      "xs",
      "sm",
      "md",
      "lg",
      "xl",
      "2xl",
      "3xl",
      "4xl",
      "5xl",
      "6xl",
      "7xl",
      "8xl",
      "9xl",
    ],
    textLeading: [0.01, 0, 2],
    textKerning: [0.01, 0, 2],
    textWeight: [100, 0, 700],
    textCase: ["uppercase", "lowercase", "capitalize"],
    textAlign: ["center", "start", "end", "justify"],
    textOverflow: ["visible", "wrap", "clip", "ellipsis"],
    textColor: ["none", ...colorNames],
    textStrokeColor: ["none", ...colorNames],
    textStrokeWidth: [1, 0, 10],
    textDecorationThickness: [1, 0, 10],
    textUnderlineOffset: [1, 0, 10],
    bgColor: ["none", ...colorNames],
    bgGradient: ["none", ...gradientNames],
    bgPattern: ["none", ...patternNames],
    bgImage: ["none", ...imageNames],
    bgAlign: ["center", "top", "bottom", "left", "right"],
    bgFit: ["contain", "cover"],
    clip: ["circle", ...pathNames],
    borderColor: ["none", ...colorNames],
    borderWidth: [1, 0, 10],
    shadow: [1, 0, 5],
    shadowInset: [1, 0, 5],
    blur: [1, 0, 10],
    brightness: [1.01, 0, 1],
    contrast: [1.01, 0, 1],
    grayscale: [1.01, 0, 1],
    hue: [1, 0, 360],
    invert: [1.01, 0, 1],
    sepia: [1.01, 0, 1],
    saturate: [1.01, 0, 1],
    blend: [
      "normal",
      "multiply",
      "screen",
      "overlay",
      "darken",
      "lighten",
      "color-dodge",
      "color-burn",
      "hard-light",
      "soft-light",
      "difference",
      "exclusion",
      "hue",
      "saturation",
      "color",
      "luminosity",
    ],
    opacity: [1.01, 0, 1],
    translateX: [1, 0, 100],
    translateY: [1, 0, 100],
    translateZ: [1, 0, 100],
    rotateX: [1, 0, 360],
    rotateY: [1, 0, 360],
    rotateZ: [1, 0, 360],
    scaleX: [0.01, 0, 4],
    scaleY: [0.01, 0, 4],
    scaleZ: [0.01, 0, 4],
    skewX: [0.01, 0, 2],
    skewY: [0.01, 0, 2],
    pivot: ["center", "top", "left", "bottom", "right"],
    delay: [1, 0, 100],
    duration: [1, 0, 100],
    ease: [
      "linear",
      "ease",
      "ease-in",
      "ease-out",
      "ease-in-out",
      "ease-in-sine",
      "ease-in-sine",
      "ease-out-sine",
      "ease-in-out-sine",
      "ease-in-quad",
      "ease-out-quad",
      "ease-in-out-quad",
      "ease-in-cubic",
      "ease-out-cubic",
      "ease-in-out-cubic",
      "ease-in-quart",
      "ease-out-quart",
      "ease-in-out-quart",
      "ease-in-quint",
      "ease-out-quint",
      "ease-in-out-quint",
      "ease-in-expo",
      "ease-out-expo",
      "ease-in-out-expo",
      "ease-in-circ",
      "ease-out-circ",
      "ease-in-out-circ",
      "ease-in-back",
      "ease-out-back",
      "ease-in-out-back",
      ...easeNames,
    ],
    animate: ["spin", "ping", "bounce", "blink", "sheen", ...animationNames],
  };
};
