// AUTO-GENERATED — do not edit by hand.
// Mirrors the sparkle prop surface from
//   packages/sparkle-style-transformer/src/constants/STYLE_TRANSFORMERS.ts (canonical names)
//   packages/sparkle-style-transformer/src/constants/STYLE_ALIASES.ts      (short aliases)
// Regenerate with: node packages/sparkdown/scripts/genSparkleStyleProps.ts
// Used by lowerLuauStyle to validate `style` block property names and
// de-alias them to their canonical sparkle spelling for the engine.

export const CANONICAL_STYLE_PROPS: ReadonlySet<string> = new Set([
  "displayed",
  "position",
  "aspect",
  "overflow",
  "overflow-x",
  "overflow-y",
  "z",
  "width",
  "width-min",
  "width-max",
  "height",
  "height-min",
  "height-max",
  "corner",
  "corner-top-left",
  "corner-top-right",
  "corner-bottom-right",
  "corner-bottom-left",
  "outline-width",
  "outline-color",
  "outline-style",
  "border-width",
  "border-width-top",
  "border-width-right",
  "border-width-bottom",
  "border-width-left",
  "border-color",
  "border-color-top",
  "border-color-right",
  "border-color-bottom",
  "border-color-left",
  "border-style",
  "border-style-top",
  "border-style-right",
  "border-style-bottom",
  "border-style-left",
  "anchor",
  "anchor-top",
  "anchor-right",
  "anchor-bottom",
  "anchor-left",
  "anchor-id",
  "anchor-to",
  "anchor-placement",
  "anchor-bounds",
  "anchor-try",
  "anchor-try-fallbacks",
  "anchor-try-order",
  "anchor-visibility",
  "margin",
  "margin-top",
  "margin-right",
  "margin-bottom",
  "margin-left",
  "padding",
  "padding-top",
  "padding-right",
  "padding-bottom",
  "padding-left",
  "child-layout",
  "child-columns",
  "child-gap",
  "child-align",
  "child-justify",
  "child-overflow",
  "self-align",
  "flex",
  "grow",
  "shrink",
  "basis",
  "order",
  "visible",
  "interactable",
  "selectable",
  "cursor",
  "text-font",
  "text-size",
  "text-leading",
  "text-tracking",
  "text-weight",
  "text-style",
  "text-case",
  "text-align",
  "text-overflow",
  "text-whitespace",
  "text-color",
  "text-stroke",
  "text-decoration-line",
  "text-decoration-color",
  "text-decoration-thickness",
  "text-underline-offset",
  "background-color",
  "background-image",
  "background-repeat",
  "background-align",
  "background-fit",
  "mask",
  "shadow",
  "shadow-inset",
  "glow",
  "ring",
  "filter",
  "backdrop-filter",
  "blend",
  "opacity",
  "translate",
  "rotate",
  "scale",
  "pivot",
  "transition-delay",
  "transition-duration",
  "transition-easing",
  "transition-property",
  "animation",
  "animation-delay",
  "animation-duration",
  "animation-easing",
  "animation-iterations",
  "animation-direction",
  "animation-fill",
  "animation-state",
  "content-visibility",
  "contain-intrinsic-size",
  "fill-color",
  "track-color",
  "thumb-background-color",
  "thumb-border-color",
  "thumb-size",
]);

export const STYLE_PROP_ALIASES: Readonly<Record<string, string>> = {
  "c": "corner",
  "c-tl": "corner-top-left",
  "c-tr": "corner-top-right",
  "c-br": "corner-bottom-right",
  "c-bl": "corner-bottom-left",
  "o-width": "outline-width",
  "o-color": "outline-color",
  "o-style": "outline-style",
  "b-width": "border-width",
  "b-width-t": "border-width-top",
  "b-width-r": "border-width-right",
  "b-width-b": "border-width-bottom",
  "b-width-l": "border-width-left",
  "b-color": "border-color",
  "b-color-t": "border-color-top",
  "b-color-r": "border-color-right",
  "b-color-b": "border-color-bottom",
  "b-color-l": "border-color-left",
  "b-style": "border-style",
  "b-style-t": "border-style-top",
  "b-style-r": "border-style-right",
  "b-style-b": "border-style-bottom",
  "b-style-l": "border-style-left",
  "a": "anchor",
  "a-t": "anchor-top",
  "a-r": "anchor-right",
  "a-b": "anchor-bottom",
  "a-l": "anchor-left",
  "i": "anchor",
  "i-t": "anchor-top",
  "i-r": "anchor-right",
  "i-b": "anchor-bottom",
  "i-l": "anchor-left",
  "m": "margin",
  "m-t": "margin-top",
  "m-r": "margin-right",
  "m-b": "margin-bottom",
  "m-l": "margin-left",
  "p": "padding",
  "p-t": "padding-top",
  "p-r": "padding-right",
  "p-b": "padding-bottom",
  "p-l": "padding-left",
  "w": "width",
  "w-min": "width-min",
  "w-max": "width-max",
  "h": "height",
  "h-min": "height-min",
  "h-max": "height-max",
  "bg-color": "background-color",
  "bg-image": "background-image",
  "bg-repeat": "background-repeat",
  "bg-align": "background-align",
  "bg-fit": "background-fit",
};

// Resolve an authored style property name to its canonical sparkle
// spelling. Returns null if the name is neither a canonical prop nor a
// known alias (the caller emits an “unknown style property” diagnostic).
export function resolveStyleProp(name: string): string | null {
  const canonical = STYLE_PROP_ALIASES[name] ?? name;
  return CANONICAL_STYLE_PROPS.has(canonical) ? canonical : null;
}
