const getReadOnlyFields = (): string[] => {
  return [
    "score",
    "rating",
    "rank",
    "likes",
    "dislikes",
    "kudos",
    "contributions",
    "comments",
    "removed",
    "daysWhenWeekOld",
    "hoursWhenDayOld",
    "monthsWhenYearOld",
    "weeksWhenMonthOld",
    "nsfw",
    "terms",
    "flagged",
    "og",
    "delisted",
    "_serverUpdatedAt",
    "_aggregatedAt",
    "connects",
    "follows",
    "reports",
    "my_connects",
    "my_dislikes",
    "my_follows",
    "my_kudos",
    "my_likes",
    "my_submissions",
  ];
};

export default getReadOnlyFields;
