export type DataDocumentType =
  | "PathDocument"
  | "UserDocument"
  | "StudioDocument"
  | "ProjectDocument"
  | "CommentDocument"
  | "NoteDocument"
  | "ContributionDocument"
  | "ClaimsDocument"
  | "SettingsDocument"
  | "SlugDocument"
  | "TagDocument"
  | "PhraseDocument"
  | "SuggestionDocument"
  | "CustomizationDocument";
