// Ambient declaration for the Emscripten-built Luau.Web.js module. The
// actual JS file is generated by `npm run build:wasm` and is gitignored, so
// we declare its shape here to keep `tsc --noEmit` green even before the
// first WASM build.

declare module "*/Luau.Web.js" {
  type EmscriptenModule = {
    ccall: (
      name: string,
      returnType: "string" | "number" | null,
      argTypes: Array<"string" | "number">,
      args: Array<string | number>
    ) => string | number | null;
    cwrap: (
      name: string,
      returnType: "string" | "number" | null,
      argTypes: Array<"string" | "number">
    ) => (...args: Array<string | number>) => string | number | null;
  };

  type EmscriptenModuleFactory = (
    config?: Partial<{
      print: (text: string) => void;
      printErr: (text: string) => void;
      locateFile: (path: string) => string;
    }>
  ) => Promise<EmscriptenModule>;

  const createLuauModule: EmscriptenModuleFactory;
  export default createLuauModule;
}
