export type ConfigKey =
  | "abbreviations"
  | "capitalizations"
  | "colors"
  | "gameTags"
  | "messages"
  | "moods"
  | "phrases"
  | "regexes"
  | "resourceTags"
  | "roleTags"
  | "tagColorNames"
  | "tagDisambiguations"
  | "tagIconNames"
  | "tagPatterns"
  | "terms";
