export type Message =
  | "pitched_games_preamble"
  | "pitched_games_author_preamble"
  | "pitched_game_preamble"
  | "pitched_game_author_preamble"
  | "pitched_story_preamble"
  | "pitched_story_author_preamble"
  | "pitched_character_preamble"
  | "pitched_character_author_preamble"
  | "pitched_setting_preamble"
  | "pitched_setting_author_preamble"
  | "pitched_music_preamble"
  | "pitched_music_author_preamble"
  | "pitched_sound_preamble"
  | "pitched_sound_author_preamble"
  | "pitched_voice_preamble"
  | "pitched_voice_author_preamble"
  | "contribute_type_label";
