import {
  random_graphic_default,
  random_graphic_zigzag,
  random_graphic_bubble,
  random_graphic_circle,
  random_graphic_grid,
  random_graphic_herringbone,
  random_graphic_flower,
  random_graphic_equal,
  random_graphic_mat,
  random_graphic_memphis,
  random_graphic_net,
  random_graphic_octagon,
  random_graphic_plus,
  random_graphic_brick,
  random_graphic_tile,
  random_graphic_wave,
} from "./constructors/random_graphic";

export const uiRandomDefinitions = () => ({
  graphic: {
    "$random:default": random_graphic_default(),
    "$random:zigzag": random_graphic_zigzag(),
    "$random:bubble": random_graphic_bubble(),
    "$random:circle": random_graphic_circle(),
    "$random:grid": random_graphic_grid(),
    "$random:herringbone": random_graphic_herringbone(),
    "$random:flower": random_graphic_flower(),
    "$random:equal": random_graphic_equal(),
    "$random:mat": random_graphic_mat(),
    "$random:memphis": random_graphic_memphis(),
    "$random:net": random_graphic_net(),
    "$random:octagon": random_graphic_octagon(),
    "$random:plus": random_graphic_plus(),
    "$random:brick": random_graphic_brick(),
    "$random:tile": random_graphic_tile(),
    "$random:wave": random_graphic_wave(),
  } as Record<string, ReturnType<typeof random_graphic_default>>,
});
