export const ARIA_PROPERTY_NAME_MAP = {
  ariaAtomic: "aria-atomic",
  ariaAutoComplete: "aria-autocomplete",
  ariaBusy: "aria-busy",
  ariaChecked: "aria-checked",
  ariaColCount: "aria-colcount",
  ariaColIndex: "aria-colindex",
  ariaColSpan: "aria-colspan",
  ariaCurrent: "aria-controls",
  ariaDisabled: "aria-disabled",
  ariaExpanded: "aria-expanded",
  ariaHasPopup: "aria-haspopup",
  ariaHidden: "aria-hidden",
  ariaInvalid: "aria-invalid",
  ariaKeyShortcuts: "aria-keyshortcuts",
  ariaLabel: "aria-label",
  ariaLevel: "aria-level",
  ariaLive: "aria-live",
  ariaModal: "aria-modal",
  ariaMultiLine: "aria-multiline",
  ariaMultiSelectable: "aria-multiselectable",
  ariaOrientation: "aria-orientation",
  ariaPlaceholder: "aria-placeholder",
  ariaPosInSet: "aria-posinset",
  ariaPressed: "aria-pressed",
  ariaReadOnly: "aria-readonly",
  ariaRequired: "aria-required",
  ariaRoleDescription: "aria-roledescription",
  ariaRowCount: "aria-rowcount",
  ariaRowIndex: "aria-rowindex",
  ariaRowSpan: "aria-rowspan",
  ariaSelected: "aria-selected",
  ariaSetSize: "aria-setsize",
  ariaSort: "aria-sort",
  ariaValueMax: "aria-valuemax",
  ariaValueMin: "aria-valuemin",
  ariaValueNow: "aria-valuenow",
  ariaValueText: "aria-valuetext",
  role: "role",
  tabIndex: "tabindex",
  hidden: "hidden",
} as const;

export const ARIA_ATTRIBUTE_NAME_MAP = {
  ariaActiveDescendant: "aria-activedescendant",
  ariaDescribedBy: "aria-describedby",
  ariaDescription: "aria-description",
  ariaDetails: "aria-details",
  ariaDropEffect: "aria-dropeffect",
  ariaErrorMessage: "aria-errormessage",
  ariaFlowTo: "aria-flowto",
  ariaGrabbed: "aria-grabbed",
  ariaLabelledBy: "aria-labelledby",
  ariaOwns: "aria-owns",
  ariaRelevant: "aria-relevant",
} as const;
