import { nodeNameSet } from "../../utils/nodeNameSet";

// Grammar nodes used to classify statement boundaries and callable values.
// Keep the names explicit so the typecheck catches renamed or removed rules.

export const LUAU_BLOCK_NAMES = nodeNameSet([
  "LuauStructBlock",
  "LuauStructListBlock",
  "LuauSparkleElementBlock",
  "LuauSparkleControlBlock",
  "LuauSparkleIfBlock",
  "LuauSparkleElseifBlock",
  "LuauSparkleElseBlock",
  "LuauSparkleForLoop",
  "LuauSparkleMatchBlock",
  "LuauControlBlock",
  "LuauForLoop",
  "LuauWhileLoop",
  "LuauRepeatLoop",
  "LuauDoBlock",
  "LuauIfBlock",
  "LuauElseifBlock",
  "LuauElseBlock",
  "LuauConditionalAlternatorBlock",
  "LuauSequentialAlternatorBlock",
]);

export const BLOCK_NAMES = nodeNameSet([
  "LuauSparkdownInlineGluedSequentialAlternatorBlock",
  "LuauSparkdownInlineGluedConditionalAlternatorBlock",
  "FrontMatterStringBlock",
  "LuauStructBlock",
  "LuauStructListBlock",
  "LuauSparkleElementBlock",
  "LuauSparkleControlBlock",
  "LuauSparkleIfBlock",
  "LuauSparkleElseifBlock",
  "LuauSparkleElseBlock",
  "LuauSparkleForLoop",
  "LuauSparkleMatchBlock",
  "LuauSparkdownControlBlock",
  "LuauControlBlock",
  "LuauSparkdownForLoop",
  "LuauForLoop",
  "LuauSparkdownWhileLoop",
  "LuauWhileLoop",
  "LuauSparkdownRepeatLoop",
  "LuauRepeatLoop",
  "LuauSparkdownDoBlock",
  "LuauDoBlock",
  "LuauSparkdownIfBlock",
  "LuauIfBlock",
  "LuauSparkdownElseifBlock",
  "LuauElseifBlock",
  "LuauSparkdownElseBlock",
  "LuauElseBlock",
  "LuauSparkdownChooseBlock",
  "LuauSparkdownAlternatorBlocks",
  "LuauAlternatorBlocks",
  "LuauSparkdownConditionalAlternatorBlock",
  "LuauConditionalAlternatorBlock",
  "LuauSparkdownSequentialAlternatorBlock",
  "LuauSparkdownSingleLineSequentialAlternatorBlock",
  "LuauSparkdownSingleLineConditionalAlternatorBlock",
  "LuauSequentialAlternatorBlock",
]);

export const NARRATIVE_STATEMENT_NAMES = nodeNameSet([
  "LuauSparkdownInlineGluedSequentialAlternatorBlock",
  "LuauSparkdownInlineGluedConditionalAlternatorBlock",
  "LuauSparkdownInlineGluedAlternatorArm",
  "LuauSparkdownAlternatorArm",
  "LuauSparkdownReassignment",
  "LuauSparkdownVariableDefinition",
  "LuauSparkdownControlBlock",
  "LuauSparkdownBlockBody",
  "LuauSparkdownForLoop",
  "LuauSparkdownWhileLoop",
  "LuauSparkdownRepeatLoop",
  "LuauSparkdownDoBlock",
  "LuauSparkdownIfBlock",
  "LuauSparkdownElseifBlock",
  "LuauSparkdownElseBlock",
  "LuauSparkdownChooseBlock",
  "LuauSparkdownChooseThenClause",
  "LuauSparkdownAlternatorBlocks",
  "LuauSparkdownConditionalAlternatorBlock",
  "LuauSparkdownSequentialAlternatorBlock",
  "LuauSparkdownSingleLineSequentialAlternatorBlock",
  "LuauSparkdownSingleLineConditionalAlternatorBlock",
  "LuauSparkdownReturnStatement",
]);

export const CALLEE_END_NAMES = nodeNameSet([
  "PunctuationParenClose",
  "PunctuationBracketClose",
  "LuauStylePropertyName",
  "StylingDeclarationScalarPropertyName",
  "OperatorPrefixedPropertyName",
  "PropertyName",
  "StylingFunctionName",
  "VariableName",
  "InvalidSelectorPropertyName",
  "LuauFunctionName",
  "LuauSelfKeyword",
  "LuauPropertyName",
  "LuauVariableName",
  "LuauStdLibGlobals",
  "LuauStdLibFunctions",
  "LuauStdLibConstants",
  "LuauStdLibMethods",
  "LuauTypeFunctionName",
  "LuauTypeofFunctionName",
  "LuauTypePropertyName",
]);
