export enum CommandTypeId {
  LogCommand = "LogCommand",
  DoCommand = "DoCommand",
  EnterCommand = "EnterCommand",
  ExitCommand = "ExitCommand",
  EndCommand = "EndCommand",
  WaitCommand = "WaitCommand",
  IfCommand = "IfCommand",
  ElseIfCommand = "ElseIfCommand",
  ElseCommand = "ElseCommand",
  SelectCommand = "SelectCommand",
  CloseCommand = "CloseCommand",
  SetCommand = "SetCommand",
  SayCommand = "SayCommand",
  CreateCommand = "CreateCommand",
  DestroyCommand = "DestroyCommand",
  ShowImageCommand = "ShowImageCommand",
  MoveToImageCommand = "MoveToImageCommand",
  RotateToImageCommand = "RotateToImageCommand",
  ScaleToImageCommand = "ScaleToImageCommand",
  HideImageCommand = "HideImageCommand",
  PlayAudioCommand = "PlayAudioCommand",
  PauseAudioCommand = "PauseAudioCommand",
  ResumeAudioCommand = "ResumeAudioCommand",
  StopAudioCommand = "StopAudioCommand",
  ShowPortraitCommand = "ShowPortraitCommand",
}
