comments:
  lineComment: "//"
  blockComment: ["/*", "*/"]

brackets:
  - ["{", "}"]
  - ["[", "]"]
  - ["(", ")"]

colorizedBracketPairs:
  - ["{", "}"]

autoClosingPairs:
  - open: "{"
    close: "}"
  - open: "["
    close: "]"
  - open: "("
    close: ")"
  - open: "<"
    close: ">"
    notIn: ["DialogueCharacterPosition"]
  - open: '"'
    close: '"'
  - open: "=== "
    close: " ==="
  - open: "== "
    close: " =="
  - open: "~~"
    close: "~~"
  - open: "::"
    close: "::"

surroundingPairs:
  - ["{", "}"]
  - ["[", "]"]
  - ["(", ")"]
  - ["<", ">"]
  - ['"', '"']
  - ["*", "*"]
  - ["_", "_"]
  - ["~", "~"]
  - [":", ":"]
  - ["^", "^"]

wordChars: _'

wordPattern:
  pattern: (\p{L}|\p{N}|\p{Mn})(((\p{L}|\p{N}|\p{Mn})|[_]|['])?(\p{L}|\p{N}|\p{Mn}))*
  flags: u

onEnterRules:
  - beforeText: \{\s*$
    afterText: \s*\}
    action:
      indent: "indentOutdent"
      appendText: "- "
  - beforeText: \{[^{}]*
    afterText: \s*\}
    action:
      indent: "indentOutdent"
  - beforeText: \{\s*$
    afterText: (?!\s*\})
    action:
      indent: "none"
      appendText: "- "
  - beforeText: \s*[-]\s+.*?$
    action:
      indent: "none"
      appendText: "- "
  - beforeText: \s*[+]\s+.*?(\[.*?\]|[-][>]).*?$
    action:
      indent: "none"
      appendText: "+ "
  - beforeText: \s*[*]\s+.*?(\[.*?\]|[-][>]).*?$
    action:
      indent: "none"
      appendText: "* "
  - beforeText: \s*[+]\s+.*?(?!\[.*?\]|[-][>]).*?$
    action:
      indent: "indent"
  - beforeText: \s*[*]\s+.*?(?!\[.*?\]|[-][>]).*?$
    action:
      indent: "indent"
  - beforeText: \[\s*$
    afterText: ^\s*\].*$
    action:
      indent: "indentOutdent"
  - beforeText: \[\s*$
    afterText: ^(?!\s*\])
    action:
      indent: "indent"
  - beforeText: \(\s*$
    afterText: ^\s*\).*$
    action:
      indent: "indentOutdent"
  - beforeText: \(\s*$
    afterText: ^(?!\s*\))
    action:
      indent: "indent"
  - beforeText: ^\s*(?![%]\s+).*?[:]\s*$
    action:
      indent: "indent"
  - beforeText: ^\s*(?:[-])\s*$
    action:
      indent: "indent"
  - beforeText: ^\s*(?:[-])\s+.*(?:\s[=]\s).*$
    action:
      indent: "indent"
  - beforeText: ^\s*(?:[%]\s+).*?[\\]\s*$
    action:
      indent: "indent"
  - beforeText: ^\s*(?:[$]\s+).*?[\\]\s*$
    action:
      indent: "indent"
  - beforeText: ^\s*(?:[!]\s+).*?[\\]\s*$
    action:
      indent: "indent"
  - beforeText: ^\s*(?:[@]\s+.*?[:]).*?[\\]\s*$
    action:
      indent: "indent"
  - beforeText: ^\s*$
    action:
      indent: "none"
      deleteText: "  "
  - beforeText: ^\s*
    action:
      indent: "none"
