comments:
  lineComment: "%%"

brackets:
  - ["{", "}"]
  - ["[", "]"]
  - ["(", ")"]

autoClosingPairs:
  - open: "{"
    close: "}"
  - open: "["
    close: "]"
  - open: "("
    close: ")"
  - open: "`"
    close: "`"
  - open: '"'
    close: '"'

surroundingPairs:
  - ["{", "}"]
  - ["[", "]"]
  - ["(", ")"]
  - ["`", "`"]
  - ['"', '"']
  - ["'", "'"]
  - ["*", "*"]
  - ["_", "_"]
  - ["~", "~"]
  - ["=", "="]
  - [":", ":"]
  - ["^", "^"]
  - ["/", "/"]
  - ["\\", "\\"]
  - ["|", "|"]
  - ["<", ">"]

wordChars: _'

wordPattern:
  pattern: (\p{L}|\p{N}|\p{Mn})(((\p{L}|\p{N}|\p{Mn})|[_]|['])?(\p{L}|\p{N}|\p{Mn}))*
  flags: u

onEnterRules:
  - beforeText: ^\s*(?:[_a-zA-Z][_a-zA-Z0-9]*).*?[:]\s*$
    action: { indent: "indent" }
  - beforeText: \{\s*$
    afterText: \}.*$
    action: { indent: "indentOutdent" }
  - beforeText: ^.*$
    afterText: \}.*$
    action: { indent: "outdent" }
  - beforeText: \{\s*$
    afterText: (?!\})
    action: { indent: "indent" }
  - beforeText: \[\s*$
    afterText: \].*$
    action: { indent: "indentOutdent" }
  - beforeText: ^.*$
    afterText: \].*$
    action: { indent: "outdent" }
  - beforeText: \[\s*$
    afterText: (?!\])
    action: { indent: "indent" }
  - beforeText: \(\s*$
    afterText: \).*$
    action: { indent: "indentOutdent" }
  - beforeText: ^.*$
    afterText: \).*$
    action: { indent: "outdent" }
  - beforeText: \(\s*$
    afterText: (?!\))
    action: { indent: "indent" }
