comments:
  lineComment: "%%"

brackets:
  - ["{", "}"]
  - ["[", "]"]
  - ["(", ")"]

autoClosingPairs:
  - open: "{"
    close: "}"
  - open: "["
    close: "]"
  - open: "("
    close: ")"
  - open: "`"
    close: "`"
  - open: '"'
    close: '"'

surroundingPairs:
  - ["{", "}"]
  - ["[", "]"]
  - ["(", ")"]
  - ["`", "`"]
  - ['"', '"']
  - ["'", "'"]
  - ["*", "*"]
  - ["_", "_"]
  - ["~", "~"]
  - ["=", "="]
  - [":", ":"]
  - ["^", "^"]
  - ["/", "/"]
  - ["\\", "\\"]
  - ["|", "|"]
  - ["<", ">"]

wordChars: _'

wordPattern:
  pattern: (\p{L}|\p{N}|\p{Mn})(((\p{L}|\p{N}|\p{Mn})|[_])?(\p{L}|\p{N}|\p{Mn}))*
  flags: u

indentationRules:
  increaseIndentPattern: (^[ \t]*(?:if|elseif|else|repeat)\b(?:(?!\b(end)\b).)*)|(\{\s*$)|(\[\s*$)|(\(\s*$)|(^[ \t]+.*[:]\s*$)
  decreaseIndentPattern: ^\s*((\b(elseif|else|end)\b)|(\})|(\])|(\))|[-]{3,})
