import { Container as RuntimeContainer } from "../../../../engine/Container";
import { ControlCommand as RuntimeControlCommand } from "../../../../engine/ControlCommand";
import { Expression } from "./Expression";

// Call an arbitrary expression value (closure, DivertTargetValue, or
// `__call`-equipped table) with a list of pre-evaluated args. The
// expression evaluates to the callable; runtime `CallValueAsFunction`
// pops it (and the args below it), then dispatches via the same path
// closure literals and direct DivertTargetValue calls use.
//
// Used by `lowerMethodCall` when the method receiver isn't a stdlib
// namespace — sparkdown can't statically resolve `a.method(args)` to
// a top-level flow, so it lowers to "evaluate `a.method` as a value
// and call it" instead of receiver-threading to a flow named `method`.
//
// Generated bytecode (inside the EvalStart/EvalEnd wrap that the
// base `Expression.GenerateRuntimeObject` adds):
//   <each arg, pushed in order — leaves them below the callable>
//   <targetExpression — pushes the callable on top>
//   CallValueAsFunction (pops callable; reads args; dispatches)
//   [PopEvaluatedValue]  ← only when used as a statement
//
// The return value remains on the eval stack after the call — so the
// expression can be used in any position (RHS of assignment, function
// arg, etc.). Statement-position callers set `shouldPopReturnedValue`
// to discard it.
export class CallValueExpression extends Expression {
  public readonly targetExpression: Expression;
  public readonly args: Expression[];
  public shouldPopReturnedValue: boolean = false;

  constructor(target: Expression, args: Expression[]) {
    super();
    this.targetExpression = this.AddContent(target) as Expression;
    this.args = args.map((a) => this.AddContent(a) as Expression);
  }

  get typeName(): string {
    return "CallValueExpression";
  }

  public readonly GenerateIntoContainer = (
    container: RuntimeContainer,
  ): void => {
    for (const arg of this.args) {
      arg.GenerateIntoContainer(container);
    }
    this.targetExpression.GenerateIntoContainer(container);
    container.AddContent(RuntimeControlCommand.CallValueAsFunction());
    if (this.shouldPopReturnedValue) {
      container.AddContent(RuntimeControlCommand.PopEvaluatedValue());
    }
  };

  public readonly toString = (): string =>
    `${this.targetExpression}(${this.args.map((a) => a.toString()).join(", ")})`;
}
