import { Create } from "../../../core/types/Create";
import { A } from "../constants/A";
import { Synth } from "../types/Synth";

export const default_synth: Create<Synth> = (obj) => ({
  $type: "synth",
  $name: "$default",
  $link: {
    image: {},
    audio: {},
    character: {},
    typewriter: {},
    inflection: {},
    prosody: {},
  },
  shape: "triangle",
  volume: 0.5,
  compression: 0,
  ...(obj || {}),
  envelope: {
    offset: 0,
    attack: 0.007,
    decay: 0.003,
    sustain: 0.035,
    release: 0.01,
    level: 0.5,
    ...(obj?.envelope || {}),
  },
  pitch: {
    frequency: A[4],
    frequency_ramp: 0,
    frequency_torque: 0,
    frequency_jerk: 0,
    phase: 0,
    ...(obj?.pitch || {}),
  },
  highpass: {
    on: false,
    cutoff: 2000,
    cutoff_ramp: 0,
    ...(obj?.highpass || {}),
  },
  lowpass: {
    on: false,
    cutoff: 4000,
    cutoff_ramp: 0,
    resonance: 0.5,
    ...(obj?.lowpass || {}),
  },
  wahwah: {
    on: false,
    rate: 6,
    rate_ramp: 0,
    strength: 0.5,
    strength_ramp: 0,
    shape: "sine",
    ...(obj?.wahwah || {}),
  },
  distortion: {
    on: false,
    edge: 0.5,
    edge_ramp: 0,
    grit: 0,
    grit_ramp: 0,
    ...(obj?.distortion || {}),
  },
  arpeggio: {
    on: false,
    rate: 12,
    rate_ramp: 0,
    max_octaves: 1,
    max_notes: 160,
    direction: "up",
    tones: [],
    levels: [],
    shapes: [],
    ...(obj?.arpeggio || {}),
  },
  vibrato: {
    on: false,
    rate: 6,
    rate_ramp: 0,
    strength: 0.5,
    strength_ramp: 0,
    shape: "sine",
    ...(obj?.vibrato || {}),
  },
  tremolo: {
    on: false,
    rate: 12,
    rate_ramp: 0,
    strength: 0.5,
    strength_ramp: 0,
    shape: "sine",
    ...(obj?.tremolo || {}),
  },
  reverb: {
    on: false,
    mix: 0.5,
    room_size: 0.5,
    damping: 0.2,
    ...(obj?.reverb || {}),
  },
});
