import { Create } from "../../../core/types/Create";

export const properties_style = () => ({
  position: "",
  width: "",
  height: "",
  min_width: "",
  min_height: "",
  max_width: "",
  max_height: "",
  aspect_ratio: "",
  border_radius: "",
  border_top_left_radius: "",
  border_top_right_radius: "",
  border_bottom_right_radius: "",
  border_bottom_left_radius: "",
  inset: "",
  top: "",
  right: "",
  bottom: "",
  left: "",
  margin: "",
  margin_top: "",
  margin_right: "",
  margin_bottom: "",
  margin_left: "",
  padding: "",
  padding_top: "",
  padding_right: "",
  padding_bottom: "",
  padding_left: "",
  gap: "",
  flex: "",
  flex_direction: "",
  flex_wrap: "",
  flex_grow: "",
  flex_shrink: "",
  align_self: "",
  align_items: "",
  justify_content: "",
  overflow: "",
  overflow_x: "",
  overflow_y: "",
  z_index: "",
  color: "",
  font_family: "",
  font_size: "",
  font_weight: "",
  text_align: "",
  text_wrap: "",
  text_transform: "",
  text_decoration_thickness: "",
  text_decoration_color: "",
  text_underline_offset: "",
  text_stroke: "",
  line_height: "",
  letter_spacing: "",
  background_color: "",
  background_image: { $type: "image", $name: "none" },
  background_position: "",
  background_size: "",
  mask_image: { $type: "image", $name: "none" },
  clip_path: "",
  outline_color: "",
  outline_width: "",
  border_color: "",
  border_width: "",
  box_shadow: "",
  opacity: "",
  transform: "",
  translate: "",
  rotate: "",
  scale: "",
  transform_origin: "",
  filter: "",
  backdrop_filter: "",
  mix_blend_mode: "",
  transition: "",
  transition_delay: "",
  transition_duration: "",
  transition_timing_function: "",
  animation: "",
  animation_name: "",
  animation_iteration_count: "",
  animation_play_state: "",
  animation_fill_mode: "",
  animation_direction: "",
  animation_delay: "",
  animation_duration: "",
  animation_timing_function: "",
});

export const optional_style: Create<any> = () => ({
  $type: "style",
  $name: "$optional",
  $recursive: true,
  ...properties_style(),
});
