import { Create } from "../../../core/types/Create";

export const properties_style = () => ({
  position: { $type: "layout_position" },
  width: { $type: "dimension" },
  height: { $type: "dimension" },
  min_width: { $type: "dimension" },
  min_height: { $type: "dimension" },
  max_width: { $type: "dimension" },
  max_height: { $type: "dimension" },
  aspect_ratio: { $type: "aspect_ratio" },
  border_radius: { $type: "corner" },
  border_top_left_radius: { $type: "corner" },
  border_top_right_radius: { $type: "corner" },
  border_bottom_right_radius: { $type: "corner" },
  border_bottom_left_radius: { $type: "corner" },
  inset: { $type: "inset" },
  top: { $type: "inset" },
  right: { $type: "inset" },
  bottom: { $type: "inset" },
  left: { $type: "inset" },
  margin: { $type: "margin" },
  margin_top: { $type: "margin" },
  margin_right: { $type: "margin" },
  margin_bottom: { $type: "margin" },
  margin_left: { $type: "margin" },
  padding: { $type: "padding" },
  padding_top: { $type: "padding" },
  padding_right: { $type: "padding" },
  padding_bottom: { $type: "padding" },
  padding_left: { $type: "padding" },
  gap: "",
  flex: "",
  flex_direction: { $type: "flex_direction" },
  flex_wrap: { $type: "flex_wrap" },
  flex_grow: "",
  flex_shrink: "",
  flex_basis: { $type: "flex_basis" },
  align_self: { $type: "flex_align" },
  align_items: { $type: "flex_align" },
  justify_content: { $type: "flex_justify" },
  overflow: { $type: "overflow" },
  overflow_x: { $type: "overflow" },
  overflow_y: { $type: "overflow" },
  z_index: "",
  color: { $type: "color" },
  font_family: { $type: "font", $name: "none" },
  font_size: { $type: "font_size" },
  font_weight: { $type: "font_weight" },
  text_align: { $type: "text_align" },
  text_wrap: { $type: "text_wrap" },
  text_transform: { $type: "text_transform" },
  text_decoration_thickness: "",
  text_decoration_color: { $type: "color" },
  text_underline_offset: "",
  text_stroke: { $type: "text_stroke" },
  line_height: { $type: "text_leading" },
  letter_spacing: { $type: "text_tracking" },
  background_color: { $type: "color" },
  background_image: { $type: "image", $name: "none" },
  background_position: { $type: "background_position" },
  background_size: { $type: "background_size" },
  mask_image: { $type: "image", $name: "none" },
  clip_path: { $type: "clip_path" },
  outline_color: { $type: "color" },
  outline_width: "",
  border_color: { $type: "color" },
  border_width: "",
  box_shadow: { $type: "shadow" },
  opacity: "",
  transform: "",
  translate: "",
  rotate: "",
  scale: "",
  transform_origin: { $type: "transform_origin" },
  filter: { $type: "render_filter" },
  backdrop_filter: { $type: "render_filter" },
  mix_blend_mode: { $type: "mix_blend_mode" },
  transition: "",
  transition_delay: "",
  transition_duration: "",
  transition_timing_function: { $type: "ease" },
  animation: "",
  animation_name: { $type: "animation" },
  animation_iteration_count: { $type: "animation_iteration_count" },
  animation_play_state: { $type: "animation_play_state" },
  animation_fill_mode: { $type: "animation_fill_mode" },
  animation_direction: { $type: "animation_direction" },
  animation_delay: "",
  animation_duration: "",
  animation_timing_function: { $type: "ease" },
});

export const optional_style: Create<any> = () => ({
  $type: "style",
  $name: "$optional",
  ...properties_style(),
});
