import { Create } from "../../../core/types/Create";

export const properties_style = () => ({
  displayed: true,
  visible: true,
  interactable: true,
  overflow: true,
  overflow_x: true,
  overflow_y: true,
  opacity: 1,
  margin: { $type: "[<length> | auto]" },
  margin_top: { $type: "[<length> | auto]" },
  margin_bottom: { $type: "[<length> | auto]" },
  margin_left: { $type: "[<length> | auto]" },
  margin_right: { $type: "[<length> | auto]" },
  padding: { $type: "<length>" },
  padding_top: { $type: "<length>" },
  padding_bottom: { $type: "<length>" },
  padding_left: { $type: "<length>" },
  padding_right: { $type: "<length>" },
  width: { $type: "[auto | <length> | <percentage>]" },
  width_min: { $type: "[none | <length> | <percentage>]" },
  width_max: { $type: "[none | <length> | <percentage>]" },
  height: { $type: "[auto | <length> | <percentage>]" },
  height_min: { $type: "[none | <length> | <percentage>]" },
  height_max: { $type: "[none | <length> | <percentage>]" },
  aspect_ratio: { $type: "[auto | <number>/<number>]" },
  corner: { $type: "[<length> | pill | circle]" },
  corner_top_left_radius: { $type: "[<length> | pill | circle]" },
  corner_top_right_radius: { $type: "[<length> | pill | circle]" },
  corner_bottom_right_radius: { $type: "[<length> | pill | circle]" },
  corner_bottom_left_radius: { $type: "[<length> | pill | circle]" },
  border_width: { $type: "<length>" },
  border_width_top: { $type: "<length>" },
  border_width_bottom: { $type: "<length>" },
  border_width_left: { $type: "<length>" },
  border_width_right: { $type: "<length>" },
  border_color: { $type: "color" },
  border_color_top: { $type: "color" },
  border_color_bottom: { $type: "color" },
  border_color_left: { $type: "color" },
  border_color_right: { $type: "color" },
  position: { $type: "[relative | absolute]" },
  anchor: { $type: "[auto | <length> | <percentage>]" },
  anchor_top: { $type: "[auto | <length> | <percentage>]" },
  anchor_bottom: { $type: "[auto | <length> | <percentage>]" },
  anchor_left: { $type: "[auto | <length> | <percentage>]" },
  anchor_right: { $type: "[auto | <length> | <percentage>]" },
  z: 0,
  child_layout: { $type: "[column | row]" },
  child_gap: { $type: "<length>" },
  child_align: { $type: "[stretch | start | end | center]" },
  child_justify: {
    $type: "[start | end | center | stretch | between | around | evenly]",
  },
  child_overflow: { $type: "[nowrap | wrap | wrap-reverse]" },
  align: { $type: "[start | end | center]" },
  shrink: 1,
  grow: 0,
  basis: { $type: "[auto | 0 | <length>]" },
  order: 0,
  text_font: { $type: "font" },
  text_color: { $type: "color" },
  text_size: { $type: "<length>" },
  text_leading: {
    $type: "[normal | <number> | <size> | none]",
  },
  text_tracking: { $type: "<length>" },
  text_align: { $type: "[left | center | right | justify]" },
  text_overflow: { $type: "[clip | wrap | ellipsis | visible]" },
  text_weight: { $type: "[normal | bold]" },
  text_style: { $type: "[normal | italic]" },
  text_stroke: { $type: "[<length> | <length> <color>]" },
  text_decoration_line: { $type: "[none | underline | strikethrough]" },
  text_decoration_color: { $type: "color" },
  text_decoration_thickness: { $type: "<length>" },
  text_underline_offset: { $type: "<length>" },
  text_direction: { $type: "[auto | ltr | rtl]" },
  text_case: { $type: "[none | capitalize | uppercase | lowercase]" },
  background_color: { $type: "color" },
  background_image: { $type: "image" },
  background_repeat: { $type: "[no-repeat | repeat]" },
  background_align: { $type: "[center | top | bottom | left | right]" },
  background_fit: {
    $type: "[cover | fill | contain | auto | <percentage> <percentage>]",
  },
  shadow: {
    $type: "[none | <number> | <length> <length> <length> <length> <color>]",
  },
  glow: { $type: "[none | <length> <color>]" },
  ring: { $type: "[none | <length> <color>]" },
  mask: { $type: "image" },
  blend: {
    $type:
      "[normal | plus-lighter | plus-darker | multiply | screen | overlay | darken | lighten | color-dodge | color-burn | hard-light | soft-light | difference | exclusion | hue | saturation | color | luminosity]",
  },
  filter: {
    $type:
      "[blur(<length>) | brightness(<number>) | contrast(<percentage>) | grayscale(<percentage>) | hue-rotate(<angle>) | invert(<percentage>) | opacity(<percentage>) | saturate(<percentage>) | sepia(<percentage>) | drop-shadow(<length> <length> <length> <color>)]",
  },
  backdrop_filter: {
    $type:
      "[blur(<length>) | brightness(<number>) | contrast(<percentage>) | grayscale(<percentage>) | hue-rotate(<angle>) | invert(<percentage>) | opacity(<percentage>) | saturate(<percentage>) | sepia(<percentage>) | drop-shadow(<length> <length> <length> <color>)]",
  },
  translate: { $type: "[0 0 | <length> <length> | <percentage> <percentage>]" },
  rotate: { $type: "[0 | <angle>]" },
  scale: 1,
  pivot: {
    $type: "[center | top | left | bottom | right | top left | bottom right]",
  },
  transition_delay: { $type: "<time>" },
  transition_duration: { $type: "<time>" },
  transition_easing: { $type: "ease" },
  transition_property: { $type: "<property-name>" },
  animation_name: { $type: "animation" },
  animation_state: { $type: "[running | paused]" },
  animation_delay: { $type: "<time>" },
  animation_duration: { $type: "<time>" },
  animation_easing: { $type: "ease" },
  animation_iterations: { $type: "[<number> | infinite]" },
  animation_direction: {
    $type: "[normal | reverse | alternate | alternate-reverse]",
  },
  animation_fill: { $type: "[none | forwards | backwards | both]" },
  cursor: { $type: "image" },
});

export const optional_style: Create<any> = () => ({
  $type: "style",
  $name: "$optional",
  ...properties_style(),
});
