import { CSS_ALIASES } from "../../../../../../sparkle-style-transformer/src/constants/CSS_ALIASES";
import { Create } from "../../../core/types/Create";
import { Schema } from "../../../core/types/Schema";

const GRID_STEP = 8;
const TIMING_FUNCTIONS = [
  "linear",
  "ease",
  "ease-in",
  "ease-out",
  "ease-in-out",
  "step-start",
  "step-end",
  "steps()",
  "cubic-bezier()",
];
const FILTERS = [
  "blur($1)",
  "brightness($1)",
  "contrast($1)",
  "grayscale($1)",
  "hue-rotate($1)",
  "invert($1)",
  "opacity($1)",
  "saturate($1)",
  "sepia($1)",
  "drop-shadow($1)",
];
const PROPERTY_NAMES = [
  "opacity",
  "translate",
  "rotate",
  "scale",
  "filter",
  "backdrop-filter",
  "mix-blend-mode",
  "box-shadow",
  "color",
  "background-color",
  "border-color",
  "text-decoration-color",
];
const COLORS = ["transparent", "black", "white", { $type: "color" }];

export const schema_style: Create<Schema<any>> = () => {
  const schema = {
    $type: "style",
    $name: "$schema",
    display: [true, false],
    visible: [true, false],
    interactable: [true, false],
    overflow: [true, false],
    overflow_x: [true, false],
    overflow_y: [true, false],
    opacity: [1.01, 0, 1],
    margin: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "auto"],
    margin_top: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "auto"],
    margin_bottom: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "auto"],
    margin_left: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "auto"],
    margin_right: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "auto"],
    padding: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    padding_top: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    padding_bottom: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    padding_left: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    padding_right: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    width: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "auto"],
    width_min: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "none"],
    width_max: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "none"],
    height: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "auto"],
    height_min: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "none"],
    height_max: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "none"],
    aspect_ratio: ["1/1", "16/9", "9/16", "4/5", "2/3", "2/1", "auto"],
    corner: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "pill", "circle"],
    corner_top_left_radius: [
      GRID_STEP,
      0,
      Math.pow(GRID_STEP, 2),
      "pill",
      "circle",
    ],
    corner_top_right_radius: [
      GRID_STEP,
      0,
      Math.pow(GRID_STEP, 2),
      "pill",
      "circle",
    ],
    corner_bottom_right_radius: [
      GRID_STEP,
      0,
      Math.pow(GRID_STEP, 2),
      "pill",
      "circle",
    ],
    corner_bottom_left_radius: [
      GRID_STEP,
      0,
      Math.pow(GRID_STEP, 2),
      "pill",
      "circle",
    ],
    border_width: [1, 0, 10],
    border_width_top: [1, 0, 10],
    border_width_bottom: [1, 0, 10],
    border_width_left: [1, 0, 10],
    border_width_right: [1, 0, 10],
    border_color: COLORS,
    border_color_top: COLORS,
    border_color_bottom: COLORS,
    border_color_left: COLORS,
    border_color_right: COLORS,
    position: ["relative", "absolute"],
    inset: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "auto"],
    inset_top: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "auto"],
    inset_bottom: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "auto"],
    inset_left: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "auto"],
    inset_right: [GRID_STEP, 0, Math.pow(GRID_STEP, 2), "auto"],
    z: [1, 0, 10],
    child_layout: ["row", "column"],
    child_gap: [GRID_STEP, 0, Math.pow(GRID_STEP, 2)],
    child_align: ["stretch", "start", "end", "center"],
    child_justify: [
      "start",
      "end",
      "center",
      "stretch",
      "between",
      "around",
      "evenly",
    ],
    child_overflow: ["nowrap", "wrap", "wrap-reverse"],
    align: ["start", "end", "center"],
    grow: [1, 0, 10],
    shrink: [1, 0, 10],
    basis: [1, 0, 10, "auto"],
    order: [1, 0, 10],
    text_font: ["sans", "serif", "mono", { $type: "font" }],
    text_color: COLORS,
    text_size: [
      "xs",
      "sm",
      "md",
      "lg",
      "xl",
      "2xl",
      "3xl",
      "4xl",
      "5xl",
      "6xl",
      "7xl",
      "8xl",
      "9xl",
    ],
    text_leading: [0.01, 0, 2],
    text_tracking: [0.01, 0, 2, "normal", "none"],
    text_align: ["left", "center", "right", "justify"],
    text_overflow: ["clip", "wrap", "ellipsis", "visible"],
    text_weight: [100, 0, 700, "normal", "bold"],
    text_style: ["normal", "italic"],
    text_stroke: [1, 0, 10],
    text_decoration_line: ["none", "underline", "strikethrough"],
    text_decoration_color: COLORS,
    text_decoration_thickness: [1, 0, 10],
    text_underline_offset: [1, 0, 10],
    text_direction: ["auto", "ltr", "rtl"],
    text_case: ["uppercase", "lowercase", "capitalize"],
    background_color: COLORS,
    background_image: [
      "none",
      { $type: "filtered_image" },
      { $type: "layered_image" },
      { $type: "image" },
      { $type: "graphic" },
      { $type: "gradient" },
    ],
    background_repeat: ["no-repeat", "repeat"],
    background_align: ["center", "top", "bottom", "left", "right"],
    background_fit: ["cover", "fill", "contain", "auto"],
    shadow: [1, 0, 10],
    glow: [1, 0, 10],
    ring: [1, 0, 10],
    mask: [
      "none",
      { $type: "filtered_image" },
      { $type: "layered_image" },
      { $type: "image" },
      { $type: "graphic" },
      { $type: "gradient" },
    ],
    translate: [],
    rotate: [],
    scale: [1, 0, 1],
    pivot: ["center", "top", "bottom", "left", "right"],
    blend: [
      "normal",
      "plus-lighter",
      "plus-darker",
      "multiply",
      "screen",
      "overlay",
      "darken",
      "lighten",
      "color-dodge",
      "color-burn",
      "hard-light",
      "soft-light",
      "difference",
      "exclusion",
      "hue",
      "saturation",
      "color",
      "luminosity",
    ],
    filter: FILTERS,
    backdrop_filter: FILTERS,
    transition: [],
    transition_delay: [1, 0, 100],
    transition_duration: [1, 0, 100],
    transition_easing: [...TIMING_FUNCTIONS, { $type: "ease" }],
    transition_property: PROPERTY_NAMES,
    animation: ["none", { $type: "animation" }],
    animation_name: ["none", { $type: "animation" }],
    animation_state: ["running", "pause"],
    animation_delay: [1, 0, 100],
    animation_duration: [1, 0, 100],
    animation_easing: [...TIMING_FUNCTIONS, { $type: "ease" }],
    animation_iterations: ["infinite"],
    animation_direction: [
      "normal",
      "reverse",
      "alternate",
      "alternate-reverse",
    ],
    animation_fill: ["none", "both", "forwards", "backwards"],
    cursor: [
      "none",
      { $type: "filtered_image" },
      { $type: "layered_image" },
      { $type: "image" },
      { $type: "graphic" },
      { $type: "gradient" },
    ],
  };
  for (const [prop, alias] of Object.entries(CSS_ALIASES)) {
    const aliasName = alias.replaceAll("-", "_") as keyof typeof schema;
    const schemaValue = schema[aliasName] as any;
    schema[prop as keyof typeof schema] = schemaValue;
    schema[prop.replaceAll("-", "_") as keyof typeof schema] = schemaValue;
  }
  return schema;
};
