import { RecursiveValidation } from "../../core";
import { Sound } from "../types/Sound";
import { A } from "./A";

export const SOUND_VALIDATION: RecursiveValidation<Sound> = {
  wave: [
    "sine",
    "triangle",
    "sawtooth",
    "tangent",
    "square",
    "whistle",
    "whitenoise",
    "brownnoise",
    "pinknoise",
  ],
  amplitude: {
    volume: [0.01, 0, 1],
    volumeRamp: [0.01, -1, 1],
    delay: [0.001, 0, 1],
    attack: [0.001, 0, 1],
    decay: [0.001, 0, 1],
    sustain: [0.001, 0, 1],
    release: [0.001, 0, 1],
    sustainLevel: [0.01, 0, 1],
  },
  frequency: {
    pitch: [A[1], 0, A[9]],
    pitchRamp: [0.01, -1, 1],
    accel: [0.01, -1, 1],
    jerk: [0.01, -1, 1],
    offset: [0.01, -1, 1],
  },
  lowpass: {
    cutoff: [A[1], 0, A[9]],
    cutoffRamp: [0.01, -1, 1],
    resonance: [0.01, 0, 1],
  },
  highpass: {
    cutoff: [A[2], 0, A[9]],
    cutoffRamp: [0.01, -1, 1],
  },
  distortion: {
    edge: [0.01, 0, 1],
    edgeRamp: [0.01, -1, 1],
    grit: [0.01, 0, 1],
    gritRamp: [0.01, -1, 1],
  },
  arpeggio: {
    rate: [1, 0, 1000],
    rateRamp: [0.01, -1, 1],
    maxOctaves: [1, 0, 10],
    maxNotes: [1, 0, 1000],
    direction: ["up", "down", "up-down", "down-up", "random"],
    tones: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    shapes: [
      "sine",
      "triangle",
      "sawtooth",
      "tangent",
      "square",
      "whistle",
      "brownnoise",
      "pinknoise",
      "whitenoise",
    ],
    levels: [0.01, 0, 1],
  },
  vibrato: {
    shape: ["sine", "triangle", "sawtooth", "tangent", "square", "whitenoise"],
    strength: [0.01, 0, 1],
    strengthRamp: [0.01, -1, 1],
    rate: [0.5, 0, A[0]],
    rateRamp: [0.01, -1, 1],
  },
  tremolo: {
    shape: ["sine", "triangle", "sawtooth", "tangent", "square", "whitenoise"],
    strength: [0.01, 0, 1],
    strengthRamp: [0.01, -1, 1],
    rate: [0.5, 0, A[0]],
    rateRamp: [0.01, -1, 1],
  },
  ring: {
    shape: ["sine", "triangle", "sawtooth", "tangent", "square", "whitenoise"],
    strength: [0.01, 0, 1],
    strengthRamp: [0.01, -1, 1],
    rate: [A[1], A[0], A[8]],
    rateRamp: [0.01, -1, 1],
  },
  wahwah: {
    shape: ["sine", "triangle", "sawtooth", "tangent", "square", "whitenoise"],
    strength: [0.01, 0, 1],
    strengthRamp: [0.01, -1, 1],
    rate: [0.5, 0, A[0]],
    rateRamp: [0.01, -1, 1],
  },
  harmony: {
    count: [1, 0, 10],
    falloff: [0.01, 0, 1],
    falloffRamp: [0.01, -1, 1],
    shapes: [
      "sine",
      "triangle",
      "sawtooth",
      "tangent",
      "square",
      "whistle",
      "brownnoise",
      "pinknoise",
      "whitenoise",
    ],
  },
  reverb: {
    strength: [0.01, 0, 1],
    strengthRamp: [0.01, -1, 1],
    delay: [0.01, 0, 1],
    delayRamp: [0.01, -1, 1],
  },
};
