export const FRONTMATTER_POSITIONS: Record<string, string> = {
  title: "cc",
  credit: "cc",
  author: "cc",
  source: "cc",
  notes: "bl",
  date: "br",
  draft_date: "br",
  "draft date": "br",
  contact: "br",
  contact_info: "br",
  "contact info": "br",
  revision: "br",
  copyright: "br",
  tl: "tl",
  tc: "tc",
  tr: "tr",
  cc: "cc",
  bl: "bl",
  br: "br",
  header: "header",
  footer: "footer",
  watermark: "watermark",
};
