import { MethodType } from "../types/MethodType";
import { assetTypes } from "./assetTypes";
import { structTypes } from "./structTypes";
import { tagTypes } from "./tagTypes";

export const types = [...assetTypes, ...tagTypes, ...structTypes];

export const entityMethods: MethodType[] = [
  "spawn",
  "destroy",
  "move",
  "moveX",
  "moveY",
  "moveZ",
  "rotate",
  "rotateX",
  "rotateY",
  "rotateZ",
  "scale",
  "scaleX",
  "scaleY",
];

export const assetMethods: MethodType[] = ["preload", "unload"];

export const castMethods: MethodType[] = ["string", "boolean", "number"];

export const reservedMethods: MethodType[] = [
  "log",
  "save",
  "load",
  ...castMethods,
  ...assetMethods,
  ...entityMethods,
];

export const reservedKeywords = [
  "locale",
  "any",
  "as",
  "boolean",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "constructor",
  "continue",
  "debugger",
  "declare",
  "default",
  "delete",
  "do",
  "elif",
  "else if",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "from",
  "function",
  "get",
  "if",
  "implements",
  "import",
  "in",
  "instanceof",
  "interface",
  "let",
  "module",
  "new",
  "null",
  "number",
  "object",
  "of",
  "package",
  "private",
  "protected",
  "public",
  "require",
  "return",
  "set",
  "static",
  "string",
  "super",
  "switch",
  "symbol",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
  ...types,
  ...reservedMethods,
];
