// Every case of Luau's tests/Autocomplete.test.cpp at the commit the repo's
// vendored Luau conformance suite is pinned to (see
// packages/sparkdown/src/tests/luau-conformance/upstream/VENDORING.md), in
// upstream order. A name upstream uses twice carries `#2` on its second use.
//
//   ported   the upstream snippet, placed in a function body when upstream
//            writes it at the top of a module, with its upstream expectation
//   adapted  the snippet rewritten in sparkdown syntax (`store`, `define`,
//            `//`, narrative blocks) or the expectation changed to sparkdown's,
//            with the difference stated at the test
//   n/a      no sparkdown test, for the reason given
//
// The manifest test proves each ported and adapted case has a test in one of
// the autocomplete*.test.ts files and that those files name no other case.

export const UPSTREAM_COMMIT = "c8cf2864adec33eb4eb5b4cc7e0708aa74893ba0";

export type UpstreamCase =
  | { status: "ported" | "adapted" }
  | { status: "n/a"; reason: string };

const ported: UpstreamCase = { status: "ported" };
const adapted: UpstreamCase = { status: "adapted" };
const na = (reason: string): UpstreamCase => ({ status: "n/a", reason });

const TYPES = na(
  "type-directed: the expectation comes from inferred or annotated types, which need the type checker (#589)",
);
const MODULES = na("needs modules (`require`, exported types), which sparkdown does not have");
const DEFINITIONS = na(
  "loads a Luau definition file (`declare`), which sparkdown has no equivalent of",
);
const ATTRIBUTES = na(
  "completes Luau function attributes (`@native`, `@checked`, `@deprecated`); sparkdown has none, and a top-level `@` starts a write line",
);

export const UPSTREAM_CASES: Record<string, UpstreamCase> = {
  empty_program: adapted,
  local_initializer: adapted,
  leave_numbers_alone: ported,
  user_defined_globals: adapted,
  dont_suggest_local_before_its_definition: adapted,
  recursive_function: ported,
  nested_recursive_function: adapted,
  user_defined_local_functions_in_own_definition: ported,
  global_functions_are_not_scoped_lexically: ported,
  local_functions_fall_out_of_scope: adapted,
  function_parameters: ported,
  get_member_completions: adapted,
  nested_member_completions: adapted,
  unsealed_table: ported,
  unsealed_table_2: ported,
  cyclic_table: ported,
  table_union: TYPES,
  table_intersection: TYPES,
  get_string_completions: na(
    "completes methods on a string literal, which needs the expression's type (#589)",
  ),
  get_suggestions_for_new_statement: adapted,
  get_suggestions_for_the_very_start_of_the_script: adapted,
  method_call_inside_function_body: adapted,
  method_call_inside_if_conditional: ported,
  statement_between_two_statements: ported,
  bias_toward_inner_scope: adapted,
  recommend_statement_starting_keywords: adapted,
  do_not_overwrite_context_sensitive_kws: ported,
  dont_offer_any_suggestions_from_within_a_comment: adapted,
  dont_offer_any_suggestions_from_within_a_broken_comment: ported,
  dont_offer_any_suggestions_from_within_a_broken_comment_at_the_very_end_of_the_file: ported,
  autocomplete_for_middle_keywords: adapted,
  autocomplete_for_in_middle_keywords: ported,
  autocomplete_while_middle_keywords: ported,
  autocomplete_if_middle_keywords: adapted,
  autocomplete_until_in_repeat: adapted,
  autocomplete_until_expression: adapted,
  local_names: ported,
  autocomplete_end_with_fn_exprs: ported,
  autocomplete_end_with_lambda: ported,
  autocomplete_end_of_do_block: adapted,
  stop_at_first_stat_when_recommending_keywords: ported,
  autocomplete_repeat_middle_keyword: ported,
  local_function: ported,
  "local_function#2": ported,
  local_function_params: ported,
  global_function_params: ported,
  arguments_to_global_lambda: ported,
  function_expr_params: ported,
  "local_initializer#2": adapted,
  local_initializer_2: adapted,
  "get_member_completions#2": ported,
  sometimes_the_metatable_is_an_error: ported,
  local_types_builtin: TYPES,
  private_types: TYPES,
  type_scoping_easy: TYPES,
  modules_with_types: MODULES,
  module_type_members: MODULES,
  argument_types: TYPES,
  return_types: TYPES,
  as_types: TYPES,
  function_type_types: TYPES,
  generic_types: TYPES,
  type_correct_suggestion_in_argument: TYPES,
  type_correct_suggestion_in_table: TYPES,
  type_correct_function_return_types: TYPES,
  type_correct_local_type_suggestion: TYPES,
  type_correct_function_type_suggestion: TYPES,
  type_correct_full_type_suggestion: TYPES,
  type_correct_argument_type_suggestion: TYPES,
  type_correct_expected_argument_type_suggestion: TYPES,
  type_correct_expected_argument_type_pack_suggestion: TYPES,
  type_correct_expected_return_type_suggestion: TYPES,
  type_correct_expected_return_type_pack_suggestion: TYPES,
  type_correct_expected_argument_type_suggestion_optional: TYPES,
  type_correct_expected_argument_type_suggestion_self: TYPES,
  do_not_suggest_internal_module_type: MODULES,
  suggest_external_module_type: MODULES,
  do_not_suggest_synthetic_table_name: TYPES,
  type_correct_function_no_parenthesis: TYPES,
  function_in_assignment_has_parentheses: na(
    "checks the parentheses recommendation, which comes from the function's type (#589)",
  ),
  function_result_passed_to_function_has_parentheses: na(
    "checks the parentheses recommendation, which comes from the function's type (#589)",
  ),
  type_correct_sealed_table: TYPES,
  type_correct_keywords: TYPES,
  type_correct_suggestion_for_overloads: TYPES,
  optional_members: TYPES,
  no_function_name_suggestions: adapted,
  skip_current_local: ported,
  keyword_members: ported,
  keyword_methods: ported,
  keyword_types: MODULES,
  comments: adapted,
  autocompleteProp_index_function_metamethod_is_variadic: TYPES,
  if_then_else_full_keywords: ported,
  if_then_else_elseif_completions: adapted,
  not_the_var_we_are_defining: ported,
  recursive_function_global: ported,
  recursive_function_local: ported,
  suggest_table_keys: TYPES,
  suggest_table_keys_no_initial_character: TYPES,
  suggest_table_keys_no_initial_character_2: TYPES,
  suggest_table_keys_no_initial_character_3: TYPES,
  autocomplete_documentation_symbols: DEFINITIONS,
  autocomplete_ifelse_expressions: adapted,
  autocomplete_if_else_regression: ported,
  autocomplete_interpolated_string_constant: adapted,
  autocomplete_interpolated_string_expression: adapted,
  autocomplete_interpolated_string_expression_with_comments: ported,
  autocomplete_interpolated_string_as_singleton: TYPES,
  autocomplete_explicit_type_pack: TYPES,
  autocomplete_first_function_arg_expected_type: TYPES,
  autocomplete_default_type_parameters: TYPES,
  autocomplete_default_type_pack_parameters: TYPES,
  autocomplete_oop_implicit_self: TYPES,
  autocomplete_on_string_singletons: TYPES,
  autocomplete_string_singletons_in_literal: TYPES,
  autocomplete_string_singletons: TYPES,
  string_singleton_as_table_key_iso: TYPES,
  string_singleton_as_table_key: TYPES,
  string_singleton_in_if_statement: TYPES,
  string_singleton_in_if_statement2: TYPES,
  autocomplete_string_singleton_equality: TYPES,
  autocomplete_boolean_singleton: TYPES,
  autocomplete_string_singleton_escape: TYPES,
  function_in_assignment_has_parentheses_2: TYPES,
  no_incompatible_self_calls_on_class: DEFINITIONS,
  simple: na("upstream's assertions for this case are commented out"),
  do_compatible_self_calls: adapted,
  no_incompatible_self_calls: adapted,
  no_incompatible_self_calls_2: TYPES,
  do_wrong_compatible_self_calls: TYPES,
  do_wrong_compatible_nonself_calls: na(
    "checks only the wrongIndexType flag, a type-checker judgment (#589); a method offered after a colon is do_compatible_self_calls",
  ),
  no_wrong_compatible_self_calls_with_generics: TYPES,
  string_prim_self_calls_are_fine: na(
    "completes string methods on a local, which needs the local's type (#589)",
  ),
  string_prim_non_self_calls_are_avoided: na(
    "completes string methods on a local, which needs the local's type (#589)",
  ),
  library_non_self_calls_are_fine: adapted,
  library_self_calls_are_invalid: na(
    "checks only the wrongIndexType flag, a type-checker judgment (#589); library members are library_non_self_calls_are_fine",
  ),
  source_module_preservation_and_invalidation: adapted,
  globals_are_order_independent: adapted,
  string_contents_is_available_to_callback: MODULES,
  require_by_string: MODULES,
  autocomplete_response_perf1: TYPES,
  autocomplete_subtyping_recursion_limit: TYPES,
  strict_mode_force: na(
    "forces strict type checking with a `--!nonstrict` directive; sparkdown has neither the directive nor the checker (#589)",
  ),
  suggest_exported_types: TYPES,
  "getFrontend().use_correct_global_scope": DEFINITIONS,
  string_completion_outside_quotes: MODULES,
  anonymous_autofilled_empty: TYPES,
  anonymous_autofilled_args: TYPES,
  anonymous_autofilled_args_single_return: TYPES,
  anonymous_autofilled_args_multi_return: TYPES,
  anonymous_autofilled__noargs_multi_return: TYPES,
  anonymous_autofilled__varargs_multi_return: TYPES,
  anonymous_autofilled_multi_varargs_multi_return: TYPES,
  anonymous_autofilled_multi_varargs_varargs_return: TYPES,
  anonymous_autofilled_multi_varargs_multi_varargs_return: TYPES,
  anonymous_autofilled_named_args: TYPES,
  anonymous_autofilled_partially_args: TYPES,
  anonymous_autofilled_partially_args_last: TYPES,
  anonymous_autofilled_typeof_args: TYPES,
  anonymous_autofilled_table_literal_args: TYPES,
  anonymous_autofilled_typeof_returns: TYPES,
  "anonymous_autofilled_table_literal_args#2": TYPES,
  anonymous_autofilled_typeof_vararg: TYPES,
  anonymous_autofilled_generic_type_pack_vararg: TYPES,
  anonymous_autofilled_generic_named_arg: TYPES,
  anonymous_autofilled_generic_return_type: TYPES,
  anonymous_autofilled_generic_on_argument_type_pack_vararg: TYPES,
  autocomplete_at_end_of_stmt_should_continue_as_part_of_stmt: ported,
  autocomplete_after_semicolon_should_complete_a_new_statement: adapted,
  require_tracing: MODULES,
  ac_dont_overflow_on_recursive_union: TYPES,
  type_function_has_types_definitions: TYPES,
  type_function_private_scope: TYPES,
  type_function_eval_in_autocomplete: TYPES,
  autocomplete_for_assignment: TYPES,
  autocomplete_in_local_table: TYPES,
  autocomplete_in_type_assertion: TYPES,
  autocomplete_implicit_named_index_index_expr: TYPES,
  autocomplete_implicit_named_index_index_expr_without_annotation: adapted,
  bidirectional_autocomplete_in_function_call: TYPES,
  autocomplete_via_bidirectional_self: TYPES,
  autocomplete_include_break_continue_in_loop: ported,
  autocomplete_exclude_break_continue_outside_loop: ported,
  autocomplete_exclude_break_continue_function_boundary: ported,
  autocomplete_exclude_break_continue_in_param: ported,
  autocomplete_exclude_break_continue_incomplete_while: ported,
  autocomplete_exclude_break_continue_incomplete_for: ported,
  autocomplete_exclude_break_continue_expr_func: ported,
  autocomplete_include_break_continue_in_repeat: ported,
  autocomplete_include_break_continue_in_nests: ported,
  autocomplete_exclude_break_continue_in_incomplete_loop: adapted,
  autocomplete_suggest_hot_comments: na(
    "completes `--!` mode directives, which sparkdown does not have",
  ),
  autocomplete_method_in_unfinished_repeat_body_eof: ported,
  autocomplete_method_in_unfinished_repeat_body_not_eof: ported,
  autocomplete_method_in_unfinished_while_body: ported,
  autocomplete_empty_attribute: ATTRIBUTES,
  autocomplete_deprecated_attribute: ATTRIBUTES,
  autocomplete_empty_braced_attribute: ATTRIBUTES,
  autocomplete_deprecated_braced_attribute: ATTRIBUTES,
  autocomplete_using_indexer_with_singleton_keys: TYPES,
  we_know_the_fields_of_a_class_instance: adapted,
  autocomplete_using_function_with_singleton_arg: TYPES,
  autocomplete_using_function_with_singleton_union_arg: TYPES,
  autocomplete_using_function_with_singleton_intersection_arg: TYPES,
  autocomplete_string_singleton_intersection_variable: TYPES,
  autocomplete_string_singleton_intersection_multiple: TYPES,
  autocomplete_string_singletons_in_intersection: TYPES,
  autocomplete_string_singleton_disjoint_intersection_arg: TYPES,
  autocomplete_string_singleton_keyof_intersection: TYPES,
  autocomplete_metatable_fill_writeonly_prop_no_crash: TYPES,
  autocomplete_table_insert: TYPES,
  autocomplete_react: TYPES,
  cli_197197_autocomplete_generic_keyof: TYPES,
  ac_static_method_autocomplete: adapted,
  class_autocomplete_classname_inside_method: adapted,
};
