export type EasingName =
  | "linear"
  | "ease"
  | "ease-in"
  | "ease-out"
  | "ease-in-out"
  | "ease-elastic-1"
  | "ease-elastic-2"
  | "ease-elastic-3"
  | "ease-elastic-4"
  | "ease-elastic-5"
  | "ease-squish-1"
  | "ease-squish-2"
  | "ease-squish-3"
  | "ease-squish-4"
  | "ease-squish-5";
