export const MARKDOWN_REGEX = {
  header: /(#+)(.*)/gim,
  image: /!\[([^[]+)\]\(([^)]+)\)/gim,
  src: /(\b(?:src|href)[ ]*=[ ]*)(["'])(.*?)(\2)/gm,
  link: /\[([^[]+)\]\(([^)]+)\)/gim,
  bold: /([*][*]+)(.*?)(\1)/gim,
  italic: /([*])(.*?)(\1)/gim,
  underline: /([_]+)(.*?)(\1)/gim,
  emphasis: /([\^]+|[~][~]+|[=][=]+|[>][>]+|[<][<]+|[|][|]+)(.*?)(\1)/gim,
  quote: /:"(.*?)":/gim,
  fenced_code_backtick: /([`]{3})([\S]*)([\s]?)([\s\S]+)([`]{3})/im,
  fenced_code_tilde: /([~]{3})([\S]*)([\s]?)([\s\S]+)([~]{3})/im,
  inline_code: /`([^`]+)`/gim,
  list_unordered: /\*+(.*)?/gim,
  list_ordered: /[0-9]+\.(.*)/gim,
  horizontal_rule: /\n-{5,}/gim,
  blockquote: /\n(&gt;|>)(.*)/gim,
  paragraph: /(^|\n\n)((?:(?!\n\n)[\s\S])*)/gim,
  paragraph_ignore: /^<\/?(ul|ol|li|h|p|bl|code|table|tr|td|img)/i,
  fix_list_unordered: /<\/ul>\s?<ul>/gim,
  fix_list_ordered: /<\/ol>\s<ol>/gim,
  fix_blockquote: /<\/blockquote>\s?<blockquote>/gim,
} as const;
