export const MARKDOWN_REGEX = {
  header: /(#+)(.*)/gim,
  image: /!\[([^[]+)\]\(([^)]+)\)/gim,
  link: /\[([^[]+)\]\(([^)]+)\)/gim,
  bold: /(\*\*|__)(.*?)\1/gim,
  italic: /(\*|_)(.*?)\1/gim,
  quote: /:"(.*?)":/gim,
  fenced_code_backtick: /([`]{3})([\S]*)([\s]?)([\s\S]+)([`]{3})/gim,
  fenced_code_tilde: /([~]{3})([\S]*)([\s]?)([\s\S]+)([~]{3})/gim,
  inline_code: /`([^`]+)`/gim,
  list_unordered: /\*+(.*)?/gim,
  list_ordered: /[0-9]+\.(.*)/gim,
  strikethrough: /~~(.*?)~~/gim,
  horizontal_rule: /\n-{5,}/gim,
  blockquote: /\n(&gt;|>)(.*)/gim,
  paragraph: /(^|\n\n)((?:(?!\n\n)[\s\S])*)/gim,
  paragraph_ignore: /^<\/?(ul|ol|li|h|p|bl|code|table|tr|td)/i,
  fix_list_unordered: /<\/ul>\s?<ul>/gim,
  fix_list_ordered: /<\/ol>\s<ol>/gim,
  fix_blockquote: /<\/blockquote>\s?<blockquote>/gim,
} as const;
