// Generates `src/compiler/constants/validStyleProps.json` — the set of prop
// names a Sparkle element `#prop=value` (or a `style` block key) may use without
// warning. The set is the union of:
//   - every standard/vendor CSS property (mdn-data) — Sparkle passes unknown
//     props straight through to CSS, so any real CSS property is valid;
//   - the Sparkle style vocabulary (short aliases + sparkle→CSS utility names);
//   - widget-structural props consumed by UIModule (value/checked/min/…).
// `--custom` properties and camelCase/underscore variants are handled in the
// validator, not here. Regenerate after changing the sparkle-style-transformer
// constants:  node scripts/generateValidStyleProps.ts
//
// Committed output keeps the compiler bundle self-contained (no runtime mdn-data
// / sparkle-style-transformer dependency), mirroring the generated grammar JSON.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import mdn from "mdn-data";
import { STYLE_ALIASES } from "../../sparkle-style-transformer/src/constants/STYLE_ALIASES.ts";
import { CSS_ALIASES } from "../../sparkle-style-transformer/src/constants/CSS_ALIASES.ts";
import { CSS_UTILITIES } from "../../sparkle-style-transformer/src/constants/CSS_UTILITIES.ts";

// Element-structural attributes the engine sets as real HTML attributes rather
// than CSS. Widgets (field/slider/checkbox/dropdown/option) pass EVERY prop
// through as an attribute (UIModule.mountInputWidget), and `image` takes `#src`,
// so the valid set must include common HTML attributes to avoid flagging them as
// unknown. `data-*` / `aria-*` are allowed by prefix in the validator.
const STRUCTURAL_ATTRS = [
  // form controls
  "value", "checked", "min", "max", "step", "placeholder", "disabled",
  "selected", "required", "readonly", "multiple", "size", "maxlength",
  "minlength", "pattern", "autocomplete", "autofocus", "list", "accept",
  "capture", "form", "rows", "cols", "wrap", "spellcheck", "inputmode",
  "enterkeyhint", "autocapitalize", "type", "name", "label", "for",
  // media / links / images
  "src", "srcset", "sizes", "alt", "href", "loading", "decoding", "target",
  "rel", "download", "ping", "referrerpolicy", "poster", "controls",
  "autoplay", "loop", "muted", "preload", "crossorigin",
  // universal / misc
  "id", "title", "hidden", "tabindex", "role", "lang", "dir", "draggable",
  "translate", "part", "slot", "inert", "popover", "open", "colspan",
  "rowspan", "headers", "scope",
];

const cssProps = Object.keys(mdn.css.properties).filter(
  // Drop the `--*` custom-property meta entry (custom props are always allowed,
  // handled in the validator); keep vendor-prefixed (`-webkit-*`) real props.
  (k) => !k.startsWith("--"),
);

const props = [
  ...new Set([
    ...cssProps,
    ...Object.keys(STYLE_ALIASES),
    ...Object.keys(CSS_ALIASES),
    ...Object.keys(CSS_UTILITIES),
    ...STRUCTURAL_ATTRS,
  ]),
].sort();

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(
  __dirname,
  "../src/compiler/constants/validStyleProps.json",
);
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  JSON.stringify(
    {
      $comment:
        "GENERATED by scripts/generateValidStyleProps.ts — do not edit by hand. Union of mdn-data CSS properties, the sparkle-style-transformer vocabulary, and UIModule widget props.",
      props,
    },
    null,
    0,
  ) + "\n",
);
// eslint-disable-next-line no-console
console.log(`Wrote ${props.length} valid prop names to ${outPath}`);
